(function(g){var window=this;'use strict';var MiG=function(P,v,l){g.p(function(e){P.W=g.SN(v,l);g.nx(e)})},yb=function(P){P.isActive()||P.start()},TOb=function(P,v){return v?P.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Viv=function(P){return g.Po(P)||P.V("web_enable_caption_language_preference_stickiness")},dXy=function(P,v){var l=new g.$H;
l.languageCode=P.languageCode;l.languageName=P.languageName;l.name=P.name;l.displayName=P.displayName;l.kind=P.kind;l.isDefault=!1;l.W=P.W;l.isTranslateable=P.isTranslateable;l.vssId=P.vssId;l.url=P.url;l.translationLanguage=v;P.xtags&&(l.xtags=P.xtags);P.captionId&&(l.captionId=P.captionId);return l},P6y=function(P,v){var l,e,h;
return g.p(function(z){if(z.W==1)return l=P+"|"+v,g.b(z,g.zJ(),2);if(z.W!=3){e=z.K;if(!e)throw g.Y6("gct");return g.b(z,g.Gk(e),3)}h=z.K;return z.return(h.get("captions",l))})},vry=function(P,v,l){P6y(P,v).then(function(e){e&&l(e.trackData,new g.$H(e.metadata))})},hfm=function(P){if(!lco.test(P))throw Error("'"+P+"' is not a valid hex color");
P.length==4&&(P=P.replace(efj,"#$1$1$2$2$3$3"));P=P.toLowerCase();P=parseInt(P.slice(1),16);return[P>>16,P>>8&255,P&255]},zfj=function(){var P=void 0;
P=P===void 0?{}:P;var v="suggest_correction"in g.AKo?g.AKo.suggest_correction:"Edit caption";v=v||"";var l={},e;for(e in P){l={M6:l.M6};l.M6=e;var h=function(z){return function(){return String(P[z.M6])}}(l);
v=v.replace(new RegExp("\\$\\{"+l.M6+"\\}","gi"),h);v=v.replace(new RegExp("\\$"+l.M6,"gi"),h)}return v},mTm=function(){return g.au("yt-player-caption-display-settings")},CE=function(){this.segments=[]},Rfm=function(P,v){var l=g.R4(P.segments,v);
l>=0||l<0&&(-l-1)%2===1||(l=-l-1,l>0&&v-P.segments[l-1]===1&&l<P.segments.length&&P.segments[l]-v===1?(g.MG(P.segments,l),g.MG(P.segments,l-1)):l>0&&v-P.segments[l-1]===1?P.segments[l-1]=v:l<P.segments.length&&P.segments[l]-v===1?P.segments[l]=v:(g.hK(P.segments,l,0,v),g.hK(P.segments,l+1,0,v)))},Qvj=function(P,v,l,e,h,z){g.U.call(this);
this.policy=P;this.player=v;this.Wg=l;this.S=e;this.Z=h;this.X=z;this.Y=new CE;this.T=-1;this.G=this.K=this.W=null;this.QW=0;this.j=new g.mr(this.T0,1E3,this);this.events=new g.Z1(this);g.Z(this,this.j);g.Z(this,this.events);this.events.C(v,"SEEK_COMPLETE",this.nx);this.nx();this.T0()},tpv=function(P){return P.W&&P.W.EF?P.W.EF+P.player.fh()<P.player.getCurrentTime():!1},y3o=function(P,v){if(P.policy.SI&&P.player.lw()){var l=g.WH(v,P.policy,{});
l.set("pot",P.player.lw());l=l.sQ()}else l=g.WH(v,P.policy,{}).sQ();var e={format:"RAW",withCredentials:!0};if(P.policy.Hg){e.method="POST";var h=v.Y;h&&Object.keys(h).length>0?e.postBody=g.yg(h,g.lg):e.postBody=(0,g.K5)([120,0])}P.Z&&(e.responseType="arraybuffer");var z=++P.QW,m=(0,g.Gz)();P.G=g.ia(l,e,3,100).then(function(Q){if(P.policy.kI&&z%100===1){var t=(0,g.Gz)();P.player.f0("caprsp",{rn:z,ms:t-m,kb:(Q.xhr.responseText.length/1024).toFixed()})}a:{Q=Q.xhr;P.s$();if(P.K){var y=!(P.Z?Q.response:
Q.responseText)||Q.status>=400;if(t=g.qa9(Q)){Q=g.WH(P.K,P.policy,{});P.K.Lw(Q,t);y3o(P,P.K);break a}y?P.player.f0("capfail",{status:Q.status}):(P.player.w7().LX("fcb_r"),t=P.K.N5[0].n0,P.S!=null&&P.T!==t&&(y=P.K.N5[0],P.Z?P.S(Q.response,(y.startTime+P.player.fh())*1E3):P.S(Q.responseText,(y.startTime+P.player.fh())*1E3),P.T=t))}P.K=null;P.G=null}}).bY(function(Q){P.K=null;
P.G=null;var t;P.player.f0("capfail",{rn:z,status:(t=Q.xhr)==null?void 0:t.status})});
P.K=v;Rfm(P.Y,P.K.N5[0].n0)},fE=function(P,v){g.LX.call(this,v);
this.W=P;this.J=v;this.G=null;this.T=!1;this.logger=new g.Rf("caps");this.j=g.bq(this.J.N())&&!this.W.isManifestless},fc1=function(P,v){var l=[],e;
for(e in P.W.W)if(P.W.W.hasOwnProperty(e)){var h=P.W.W[e];if(g.Gr(h,v||null)){var z=h.info.id,m=z,Q="."+z,t="",y="";if(h=h.info.captionTrack)z=h.languageCode,m=h.displayName,Q=h.vssId,t=h.kind,y=h.id;else{h=z;var C=g.TKb.get(h);C==null&&(C=C6x[h]||C6x[h.replace(/-/g,"_")],g.TKb.set(h,C));h=C;m=h||m}l.push(new g.$H({id:e,languageCode:z,languageName:m,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:t,captionId:y}))}}return l},grm=function(P,v){return v!=null&&v in P.W.W?P.W.W[v]:null},
kAo=function(P,v,l){var e=[],h;
for(h in P.W.W)if(P.W.W.hasOwnProperty(h)){var z=P.W.W[h];if(g.Gr(z,l||null)){var m=z.info.captionTrack;m&&m.languageCode===v&&e.push(z)}}return e.length?e[0]:null},gp=function(P,v,l,e,h,z,m,Q,t,y){var C=y.isInline()&&!0,f={};
Object.assign(f,v);Object.assign(f,P.params);Object.assign(f,l);var k={};Object.assign(k,v.UQ);P.params.UQ&&Object.assign(k,P.params.UQ);Object.assign(k,l.UQ);C&&(f.windowOpacity=.6,k.backgroundOpacity=0);f.UQ=k;var w=f.zJ===1,I=[{L:"span",D:"captions-text",B:{style:"word-wrap: normal; display: block;"}}],J,K,q;(Q=Q.l$("caption_edit_on_hover")&&((J=y.getVideoData().getPlayerResponse())==null?void 0:(K=J.captions)==null?void 0:(q=K.playerCaptionsTracklistRenderer)==null?void 0:q.openTranscriptCommand))&&
I.unshift({L:"button",D:"caption-edit",B:{tabindex:"0","aria-label":zfj()},U:[{L:"svg",B:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},U:[{L:"path",B:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.O.call(this,{L:"div",D:"caption-window",B:{id:"caption-window-"+P.id,dir:w?"rtl":"ltr",tabindex:"0",lang:f.lang},U:I});var A=
this;this.j=[];this.kf=!1;this.K=P;this.Hg=this.wM=null;this.playerWidth=z;this.playerHeight=m;this.S=null;this.maxWidth=z*.96;this.maxHeight=m*.96;this.W=f;this.Nd=l;this.QW=v;this.Y=this.cg("captions-text");this.jS=this.Y.style.getPropertyValue("box-decoration-break")!==""||this.Y.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.q5=wry(e,h,z,m);this.CI=t;Q&&(this.T=this.cg("caption-edit"),this.C(this.T,"click",function(){A.CI()}));
this.type=0;this.h5=this.q5*$Tv(k);this.WK=C;P=new g.e_(this.element,!0);g.Z(this,P);P.subscribe("dragstart",this.s8,this);P.subscribe("dragmove",this.Hn,this);P.subscribe("dragend",this.tG,this);this.D3=this.A5=this.Bg=this.U$=0;P="";this.W.windowOpacity&&(P=hfm(this.W.windowColor),P="rgba("+P[0]+","+P[1]+","+P[2]+","+this.W.windowOpacity+")");v={"background-color":P,display:this.W.isVisible===!1?"none":"","text-align":Icj[this.W.textAlign]};this.jS&&(v["border-radius"]=P?this.h5/8+"px":"");(this.G=
this.K.params.zJ===2||this.K.params.zJ===3)&&DT3(this,this.element);g.DO(this.element,v);if(C){var x;(x=this.element.parentElement)==null||x.style.setProperty("--caption-window-color",P)}switch(this.W.Nj){case 0:case 1:case 2:g.kk(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.kk(this.element,"ytp-caption-window-bottom")}},DT3=function(P,v){var l="vertical-rl";
P.W.gy===1&&(l="vertical-lr");g.u$&&(l=l==="vertical-lr"?"tb-lr":"tb-rl");g.DO(v,"-o-writing-mode",l);g.DO(v,"-webkit-writing-mode",l);g.DO(v,"writing-mode",l);g.DO(v,"text-orientation","upright");g.kk(v,"ytp-vertical-caption");P.K.params.zJ===3&&(g.DO(v,"text-orientation",""),g.DO(v,"transform","rotate(180deg)"))},$Tv=function(P){var v=1+.25*(P.fontSizeIncrement||0);
if(P.offset===0||P.offset===2)v*=.8;return v},nrm=function(P,v){var l={},e=v.background?v.background:P.W.UQ.background;
if(v.backgroundOpacity!=null||v.background){var h=v.backgroundOpacity!=null?v.backgroundOpacity:P.W.UQ.backgroundOpacity;e=hfm(e);l.background="rgba("+e[0]+","+e[1]+","+e[2]+","+h+")";P.jS&&(l["box-decoration-break"]="clone",l["border-radius"]=P.h5/8+"px")}if(v.fontSizeIncrement!=null||v.offset!=null)l["font-size"]=P.q5*$Tv(v)+"px";e=1;h=v.color||P.W.UQ.color;if(v.color||v.textOpacity!=null)h=hfm(h),e=v.textOpacity==null?P.W.UQ.textOpacity:v.textOpacity,h="rgba("+h[0]+","+h[1]+","+h[2]+","+e+")",
l.color=h,l.fill=h;var z=v.charEdgeStyle;z===0&&(z=void 0);if(z){h="rgba(34, 34, 34, "+e+")";var m="rgba(204, 204, 204, "+e+")";v.IW&&(m=h=v.IW);var Q=P.q5/16/2,t=Math.max(Q,1),y=Math.max(2*Q,1),C=Math.max(3*Q,1),f=Math.max(5*Q,1);e=[];switch(z){case 4:for(;C<=f;C+=Q)e.push(y+"px "+y+"px "+C+"px "+h);break;case 1:y=window.devicePixelRatio>=2?.5:1;for(z=t;z<=C;z+=y)e.push(z+"px "+z+"px "+h);break;case 2:e.push(t+"px "+t+"px "+m);e.push("-"+t+"px -"+t+"px "+h);break;case 3:for(C=0;C<5;C++)e.push("0 0 "+
y+"px "+h)}l["text-shadow"]=e.join(", ")}h="";switch(v.fontFamily){case 1:h='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:h='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:h='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:h='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:h='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:h=g.VS()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:h='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}h&&(l["font-family"]=h);h=v.offset;h==null&&(h=P.W.UQ.offset);switch(h){case 0:l["vertical-align"]="sub";break;case 2:l["vertical-align"]="super"}v.fontFamily===7&&(l["font-variant"]="small-caps");v.bold&&(l["font-weight"]="bold");v.italic&&(l["font-style"]="italic");v.underline&&(l["text-decoration"]=
"underline");v.Ef$&&(l.visibility="hidden");v.zf===1&&P.G&&(l["text-combine-upright"]="all",l["text-orientation"]="mixed",h=g.e0||g.FA,P.K.params.zJ===3?l.transform=h?"rotate(90deg)":"rotate(180deg)":h&&(l.transform="rotate(-90deg)"));if(v.Bi===1||v.Bi===2||v.Bi===3||v.Bi===4||v.Bi===5)if(g.e0)l["font-weight"]="bold";else switch(l["text-emphasis-style"]="filled circle",l["text-emphasis-color"]="currentcolor",l["webkit-text-emphasis"]="filled circle",v.Bi){case 4:case 3:l["text-emphasis-position"]=
"under left";l["webkit-text-emphasis-position"]="under left";break;case 5:case 2:l["text-emphasis-position"]="over right",l["webkit-text-emphasis-position"]="over right"}return l},kn=function(P){P=P.split("px");
return P.length>0?(P=Number(P[0]))?P:0:0},NY3=function(P){P.S=g.l5("SPAN");
g.DO(P.S,{display:"block"});g.kk(P.S,"caption-visual-line");P.Y.appendChild(P.S)},J3j=function(P,v){var l=g.l5("SPAN");
g.DO(l,{display:"inline-block","white-space":"pre-wrap"});g.DO(l,nrm(P,v));l.classList.add("ytp-caption-segment");P.S.appendChild(l);l.previousElementSibling&&(g.DO(l.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.DO(l,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return l},uNv=function(P,v,l){P.kf=P.kf||!!l;
var e={};Object.assign(e,P.W.UQ);Object.assign(e,l||v.W);Object.assign(e,P.Nd.UQ);(l=!P.S)&&NY3(P);for(var h=P.wM&&P.Hg&&g.Sp(e,P.Hg)?P.wM:J3j(P,e),z=typeof v.text==="string",m=z?v.text.split("\n"):[v.text],Q=0;Q<m.length;Q++){var t=Q>0||!v.append,y=m[Q];t&&!l?(NY3(P),h=J3j(P,e)):t&&l&&(l=!1);y&&(h.appendChild(z?g.eu(y):y),z||y.tagName!=="RUBY"||y.childElementCount!==4||g.e0||!g.N_(y.children[2],"text-emphasis")||(t=P.G?"padding-right":"padding-top",g.N_(y.children[2],"text-emphasis-position")&&(t=
P.G?"padding-left":"padding-bottom"),g.V3?g.DO(h,t,"1em"):g.DO(h,t,"0.5em")))}P.Hg=e;P.wM=h;P.j.push(v)},wry=function(P,v,l,e){var h=v/360*16;
v>=P&&(P=640,e>l*1.3&&(P=480),h=l/P*16);return h},c3d=function(){this.G=this.time=this.mode=this.K=0;
this.Y=new KtY(this);this.Z=new KtY(this);this.W=[];this.clear()},Ftd=function(P,v,l){if(P===255&&v===255||!P&&!v)return{Om:P,
MR:v,result:0};P=qqA[P];v=qqA[v];if(P&128){var e;if(e=!(v&128))e=v,e=l.n6()&&l.MR===e;if(e)return{Om:P,MR:v,result:1}}else if(v&128&&1<=P&&P<=31)return{Om:P,MR:v,result:2};return{Om:P,MR:v,result:3}},YqQ=function(P,v,l,e){v===255&&l===255||!v&&!l?(++P.G===45&&P.reset(),P.Y.K.clear(),P.Z.K.clear()):(P.G=0,A3Q(P.Y,v,l,e))},bUx=function(P,v){P.W.sort(function(h,z){var m=h.time-z.time;
return m===0?h.order-z.order:m});
for(var l=g.N(P.W),e=l.next();!e.done;e=l.next())e=e.value,P.time=e.time,e.type===0?YqQ(P,e.p_,e.kN,v):e.type===1&&P.K&496&&A3Q(P.Z,e.p_,e.kN,v);P.W.length=0},wp=function(){this.type=0},$n=function(){this.state=this.MR=this.Om=0},xTo=function(){this.timestamp=this.W=0},IU=function(P){this.Z=P;
this.G=[];this.W=this.K=this.row=0;this.style=new wp;for(P=this.Y=0;P<=15;P++){this.G[P]=[];for(var v=0;v<=32;v++)this.G[P][v]=new xTo}},D8=function(P,v){if(P.style.type===3){for(var l=0,e=0,h=P.Z.time+0,z="",m="",Q=h,t=1;t<=15;++t){for(var y=!1,C=e?e:1;C<=32;++C){var f=P.G[t][C];
if(f.W!==0){l===0&&(l=t,e=C);y=String.fromCharCode(f.W);var k=f.timestamp;k<h&&(h=k);f.timestamp=Q;m&&(z+=m,m="");z+=y;y=!0}if((f.W===0||C===32)&&y){m="\n";break}else if(e&&!y)break}if(l&&!y)break}z&&v.Y(l,e,h,Q,z)}else for(e=l=0,z=h=P.Z.time+0,m=1;m<=15;++m)for(Q="",t=1;t<=32;++t)if(C=P.G[m][t],f=C.W,f!==0&&(l===0&&(l=m,e=t),y=String.fromCharCode(f),k=C.timestamp,k<=h&&(h=k),Q+=y,C.reset()),t===32||f===0)Q&&v.Y(l,e,h,z,Q),h=z,Q="",e=l=0},Xrm=function(P,v){switch(P){case 0:return prx[(v&127)-32];
case 1:return Ltb[v&15];case 2:return Sqy[v&31];case 3:return GAy[v&31]}return 0},nE=function(P){return P.G[P.row][P.K]},NY=function(P,v,l){v>=2&&P.K>1&&(--P.K,nE(P).W=0);
var e=nE(P);e.timestamp=P.Z.time+0;e.W=Xrm(v,l);P.K<32&&P.K++},BYG=function(P,v,l,e){for(var h=0;h<e;h++)for(var z=0;z<=32;z++){var m=P.G[v+h][z],Q=P.G[l+h][z];
m.W=Q.W;m.timestamp=Q.timestamp}},Jh=function(P,v,l){for(var e=0;e<l;e++)for(var h=0;h<=32;h++)P.G[v+e][h].reset()},iU1=function(P){P.row=P.W>0?P.W:1;
P.K=1;Jh(P,0,15)},UTb=function(P){this.G=P;
this.Z=0;this.style=new wp;this.T=new IU(this.G);this.j=new IU(this.G);this.text=new IU(this.G);this.K=this.T;this.Y=this.j;this.W=this.K},ZUo=function(P,v,l){var e=P.K,h=!1;
switch(P.style.get()){case 4:case 1:case 2:P.style.get()===4&&e.W>0||(D8(e,l),iU1(P.K),iU1(P.Y),e.row=15,e.W=v,h=!0)}P.style.set(3);P.W=e;P.W.style=P.style;P.G.mode=1<<e.Y;h?e.K=1:e.W!==v&&(e.W>v?(D8(e,l),Jh(e,e.row-e.W,v)):e.row<v&&(v=e.W),e.W=v)},jvy=function(P){P.style.set(1);
P.W=P.Y;P.W.W=0;P.W.style=P.style;P.G.mode=1<<P.W.Y},acm=function(P){P.style.set(4);
P.W=P.text;P.W.style=P.style;P.G.mode=1<<P.W.Y},KtY=function(P){this.W=P;
this.Z=0;this.G=new UTb(this.W);this.T=new UTb(this.W);this.K=new $n;this.Y=this.G},A3Q=function(P,v,l,e){P.K.update();
v=Ftd(v,l,P.K);switch(v.result){case 0:return;case 1:case 2:return}var h=v.Om;l=v.MR;if(32<=h||!h)P.W.mode&P.W.K&&(v=h,v&128&&(v=127),l&128&&(l=127),P=P.Y.W,v&96&&NY(P,0,v),l&96&&NY(P,0,l),v!==0&&l!==0&&P.style.type===3&&D8(P,e));else if(h&16)a:if(!P.K.matches(h,l)&&(v=P.K,v.Om=h,v.MR=l,v.state=2,v=h&8?P.T:P.G,P.Y=v,P.W.mode=1<<(P.Z<<2)+(v.Z<<1)+(v.style.type===4?1:0),(P.W.mode|1<<(P.Z<<2)+(v.Z<<1)+(v.style.type!==4?1:0))&P.W.K))if(l&64){e=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(h&7)<<1|l>>5&1];
P=l&16?((l&14)>>1)*4:0;l=v.W;switch(v.style.get()){case 4:e=l.row;break;case 3:if(e!==l.row){if(e<l.W&&(e=l.W,e===l.row))break;var z=1+l.row-l.W,m=1+e-l.W;BYG(l,m,z,l.W);v=z;h=l.W;m<z?(z=m+h-z,z>0&&(v+=z,h-=z)):(z=z+h-m,z>0&&(h-=z));Jh(l,v,h)}}l.row=e;l.K=P+1}else switch(h&7){case 1:switch(l&112){case 32:NY(v.W,0,32);break a;case 48:l===57?(e=v.W,nE(e).W=0,e.K<32&&e.K++):NY(v.W,1,l&15)}break;case 2:l&32&&NY(v.W,2,l&31);break;case 3:l&32&&NY(v.W,3,l&31);break;case 4:case 5:if(32<=l&&l<=47)switch(l){case 32:jvy(v);
break;case 33:e=v.W;e.K>1&&(--e.K,nE(e).W=0);break;case 36:e=v.W;v=nE(e);for(P=0;P<=15;P++)for(l=0;l<=32;l++)if(e.G[P][l]===v){for(;l<=32;l++)e.G[P][l].reset();break}break;case 37:ZUo(v,2,e);break;case 38:ZUo(v,3,e);break;case 39:ZUo(v,4,e);break;case 40:NY(v.W,0,32);break;case 41:v.style.set(2);v.W=v.K;v.W.W=0;v.W.style=v.style;v.G.mode=1<<v.W.Y;break;case 42:e=v.text;e.W=15;e.style.set(4);iU1(e);acm(v);break;case 43:acm(v);break;case 44:P=v.K;switch(v.style.get()){case 1:case 2:case 3:D8(P,e)}Jh(P,
0,15);break;case 45:b:{P=v.W;switch(v.style.get()){default:case 2:case 1:break b;case 4:if(P.row<15){++P.row;P.K=1;break b}break;case 3:}P.W<2&&(P.W=2,P.row<P.W&&(P.row=P.W));v=P.row-P.W+1;D8(P,e);BYG(P,v,v+1,P.W-1);Jh(P,P.row,1)}break;case 46:Jh(v.Y,0,15);break;case 47:D8(v.K,e),v.Y.updateTime(v.G.time+0),e=v.Y,v.Y=v.K,v.K=e,jvy(v)}break;case 7:switch(l){case 33:case 34:case 35:e=v.W,(e.K+=l&3)>32&&(e.K=32)}}},HUj=function(){},uR=function(P,v,l,e,h,z,m){z=z===void 0?!1:z;
m=m===void 0?null:m;g.tn.call(this,P,P+v,{priority:l,namespace:"captions"});this.windowId=e;this.text=h;this.append=z;this.W=m},Wto=function(P,v,l,e,h,z,m){var Q=z[0],t=m[Q.getAttribute("p")];
if(t.GW===1){var y=z[1],C=z[2];z=z[3];Q.getAttribute("t");y.getAttribute("t");C.getAttribute("t");z.getAttribute("t");Q.getAttribute("p");y.getAttribute("p");z.getAttribute("p");m=m[C.getAttribute("p")];Q=Erj(Q.textContent,y.textContent,C.textContent,z.textContent,m);return new uR(P,v,h,l,Q,e,t)}switch(t.GW){case 9:case 10:t.Bi=1;break;case 11:t.Bi=2;break;case 12:t.Bi=3;break;case 13:t.Bi=4;break;case 14:t.Bi=5}return new uR(P,v,h,l,Q.textContent||"",e,t)},Erj=function(P,v,l,e,h){var z=g.VS(),m=
z?g.l5("DIV"):g.l5("RUBY"),Q=g.l5("SPAN");
Q.textContent=P;m.appendChild(Q);P=z?g.l5("DIV"):g.l5("RP");P.textContent=v;m.appendChild(P);v=z?g.l5("DIV"):g.l5("RT");v.textContent=l;m.appendChild(v);l=h.GW;if(l===10||l===11||l===12||l===13||l===14)if(g.DO(v,"text-emphasis-style","filled circle"),g.DO(v,"text-emphasis-color","currentcolor"),g.DO(v,"webkit-text-emphasis","filled circle"),h.GW===11||h.GW===13)g.DO(v,"webkit-text-emphasis-position","under left"),g.DO(v,"text-emphasis-position","under left");l=!0;if(h.GW===4||h.GW===7||h.GW===12||
h.GW===14)g.DO(m,"ruby-position","over"),g.DO(m,"-webkit-ruby-position","before");else if(h.GW===5||h.GW===6||h.GW===11||h.GW===13)g.DO(m,"ruby-position","under"),g.DO(m,"-webkit-ruby-position","after"),l=!1;h=z?g.l5("DIV"):g.l5("RP");h.textContent=e;m.appendChild(h);z&&(e=l,g.DO(m,{display:"inline-block",position:"relative"}),z=m.firstElementChild.nextElementSibling,g.DO(z,"display","none"),z=z.nextElementSibling,g.DO(z,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.DO(m.lastElementChild,"display","none"),e?(g.DO(m,"padding-top","0.6em"),g.DO(z,"top","0")):(g.DO(m,"padding-bottom","0.6em"),g.DO(z,"bottom","0")));return m},KE=function(){g.U.apply(this,arguments)},cf=function(P,v,l,e,h){g.tn.call(this,P,P+v,{priority:l,
namespace:"captions"});this.id=e;this.params=h;this.W=[]},OUd=function(P){var v="_"+qY++;
return new cf(0,0x8000000000000,0,v,P)},Fb=function(P){KE.call(this);
this.G=P;this.pens={};this.j={};this.S={};this.Y="_"+qY++;this.T={};this.K=this.W=null;this.Z=!0},Ah=function(P,v){P=P.getAttribute(v);
if(P!=null)return Number(P)},Yn=function(P,v){P=P.getAttribute(v);
if(P!=null)return P==="1"},bR=function(P,v){P=Ah(P,v);
return P!==void 0?P:null},pE=function(P,v){P=P.getAttribute(v);
if(P!=null)return xn.test(P),P},oro=function(P,v){var l={},e=v.getAttribute("ws");
Object.assign(l,e?P.S[e]:P.G);P=bR(v,"mh");P!=null&&(l.Z1=P);P=bR(v,"ju");P!=null&&(l.textAlign=P);P=bR(v,"pd");P!=null&&(l.zJ=P);P=bR(v,"sd");P!=null&&(l.gy=P);P=pE(v,"wfc");P!=null&&(l.windowColor=P);v=Ah(v,"wfo");v!==void 0&&(l.windowOpacity=v/255);return l},sv3=function(P,v){var l={},e=v.getAttribute("wp");
e&&Object.assign(l,P.j[e]);P=bR(v,"ap");P!=null&&(l.Nj=P);P=Ah(v,"cc");P!=null&&(l.Kl=P);P=Ah(v,"ah");P!=null&&(l.aK=P);P=Ah(v,"rc");P!=null&&(l.Ta=P);v=Ah(v,"av");v!=null&&(l.X6=v);return l},r3A=function(P,v,l,e){var h={};
Object.assign(h,sv3(P,v));Object.assign(h,oro(P,v));e?g.Sp(h,P.G)?(e=P.Y,h=P.G):e="_"+qY++:e=v.getAttribute("id")||"_"+qY++;P=Ah(v,"t")+l;v=Ah(v,"d")||0x8000000000000;if(h.zJ===2||h.zJ===3)l=h.Ta,h.Ta=h.Kl,h.Kl=l;return new cf(P,v,0,e,h)},LE=function(P){KE.call(this);
this.Z=P;this.W=new Map;this.G=new Map;this.Y=new Map;this.K=new Map},S7=function(P){P=g.CU(Math.round(P),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-P.length)+P},Mpm=function(P,v,l,e,h){e===0&&(e=0x8000000000000);
var z={};v.wpWinPosId&&Object.assign(z,P.G.get(v.wpWinPosId));v.wsWinStyleId&&Object.assign(z,P.Y.get(v.wsWinStyleId));P=v.rcRowCount;P!==void 0&&(z.Ta=P);v=v.ccColCount;v!==void 0&&(z.Kl=v);if(z.zJ===2||z.zJ===3)v=z.Ta,z.Ta=z.Kl,z.Kl=v;return new cf(l,e,0,h,z)},Gq=function(P,v,l){g.LX.call(this,P);
this.videoData=v;this.audioTrack=l;this.Z=v.xV},Xb=function(P,v,l,e,h,z,m,Q,t,y){gp.call(this,P,v,l,e,h,z,m,Q,t,y);
this.type=1},Bf=function(P,v,l){this.trackData=P;
this.T=l;this.version=this.Z=this.G=this.byteOffset=0;this.K=[];this.W=new DataView(this.trackData)},iR=function(P){var v=P.byteOffset;
P.byteOffset+=1;return P.W.getUint8(v)},Ud=function(P){var v=P.byteOffset;
P.byteOffset+=4;return P.W.getUint32(v)},Z8=function(P,v){KE.call(this);
this.K=P;this.G=v;this.track=this.G.languageName==="CC3"?4:0;this.W=new c3d;this.W.K=1<<this.track},Vpm=function(P){if(typeof P==="string")return!1;
P=new Bf(P,8,0);return TYj(P)},TYj=function(P){if(!(P.byteOffset<P.W.byteLength)||Ud(P)!==1380139777)return!1;
P.version=iR(P);if(P.version>1)return!1;iR(P);iR(P);iR(P);return!0},j7=function(P,v,l,e,h,z,m,Q,t,y){gp.call(this,P,v,l,e,h,z,m,Q,t,y);
var C=this;this.type=2;this.J5=[];this.Wg=this.X=this.Pg=0;this.T1=NaN;this.TG=0;this.It=null;this.Ic=new g.mr(this.aRc,433,this);this.T&&(y.createClientVe(this.T,this,167342),this.C(this.T,"click",function(){y.logClick(C.T)}),P=new g.e_(this.element,!0),g.Z(this,P),P.subscribe("hoverstart",function(){y.logVisibility(C.T,!0)},this));
g.kk(this.element,"ytp-caption-window-rollup");g.Z(this,this.Ic);g.DO(this.element,"overflow","hidden")},dTY=function(P,v){if(!v)return"";
P.G&&P.K.params.gy!==1&&(v*=-1);return"translate"+(P.G?"X":"Y")+"("+v+"px)"},P5Y=function(P){P.J5=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var v=P.K.params.Ta,l=0,e=0,h=P.J5.length-1;l<v&&h>-1;){var z=P.J5[h];e+=P.G?z.offsetWidth:z.offsetHeight;l++;h--}P.X=e;v=Math;l=v.max;isNaN(P.T1)&&((e=P.W.Kl)?(h=g.l5("SPAN"),g.tl(h,"\u2013".repeat(e)),g.DO(h,nrm(P,P.W.UQ)),P.Y.appendChild(h),P.T1=h.offsetWidth,P.Y.removeChild(h)):P.T1=0);e=P.Y;P.Wg=l.call(v,P.T1,P.TG,(P.G?e.offsetHeight:e.offsetWidth)+1)},v7x=function(P,v){P5Y(P);
var l=P.J5.reduce(function(z,m){return(P.G?m.offsetWidth:m.offsetHeight)+z},0);
l=P.X-l;if(l!==P.Pg){var e=l>0&&P.Pg===0,h=l<P.Pg;v||isNaN(l)||e||!h||(g.kk(P.element,"ytp-rollup-mode"),g.RX(P.Ic));g.DO(P.Y,"transform",dTY(P,l));P.Pg=l}P5Y(P)},lHd=function(P,v,l,e){var h=this;
this.J=P;this.K=v;this.logger=l;this.Ei=e;this.hR=[];this.Vp=[];this.Hh=null;this.Kh={mgJ:function(){return h.Hh},
AB:function(){return h.hR}};
P=g.ID(this.J.N().experiments,"html5_override_micro_discontinuities_threshold_ms");this.W=P>0?P:10},zg3=function(P,v){P.Hh=function(l,e){if(l.info.Y){var h=l;
if(P.Vp.length>0){for(h=P.Vp.shift();P.Vp.length>0;)h=g.lM(h,P.Vp.shift());h=g.lM(h,l)}if(h){l=h;try{var z=g.ea(l)*1E3}catch(y){z=l.info.startTime*1E3}try{var m=g.wBD(l)*1E3}catch(y){m=l.info.duration*1E3}if(z<0||m<0)z<0&&(z=l.info.startTime*1E3),m<0&&(m=l.info.duration*1E3);l.info.startTime=z/1E3;l.info.ao=z/1E3;l.info.duration=m/1E3;l.info.T=m/1E3;z=P.s1(h);m=z.n0;z={formatId:z.formatId,startTimeMs:z.startTimeMs,durationMs:z.durationMs,vV:m,IY:m};m=egy(P.hR,z.startTimeMs);var Q=(l=m>=0?P.hR[m]:
null)?l.startTimeMs+l.durationMs:0,t=z.startTimeMs+z.durationMs;!l||z.startTimeMs-Q>P.W?P.hR.splice(m+1,0,z):(l.durationMs=Math.max(Q,t)-l.startTimeMs,l.IY=Math.max(l.IY,z.IY));e(P.hR);e=h.f6();hgy(P.K,e.buffer.slice(e.byteOffset,e.byteLength+e.byteOffset),v,h.info.ao)}else P.logger.W(350058965,"Empty slice")}else P.Vp.push(l)};
P.J.addEventListener("sabrCaptionsDataLoaded",P.Hh)},egy=function(P,v){P=g.R4(P,{startTimeMs:v},function(l,e){return l.startTimeMs-e.startTimeMs});
return P>=0?P:-P-2},mVy=function(P,v){g.LX.call(this,v);
this.W=P;this.J=v;this.logger=new g.Rf("caps");this.G=this.T=null;this.j=new lHd(this.J,this,this.logger,this.W.Ei)},hgy=function(P,v,l,e){P.logger.debug(function(){return"SABR captions data received for "+e});
P.T?P.G==null?P.logger.W(350058965,"Null loaded track meta data at captions data received"):l.w2(v,P.G,e*1E3):P.logger.W(350058965,"Null Representation at captions data received")},Rgx=function(P,v){var l=[],e;
for(e in P.W.W)if(P.W.W.hasOwnProperty(e)){var h=P.W.W[e];if(g.Gr(h,v||null)){var z=h.info.id,m=z,Q="."+z,t="",y="";if(h=h.info.captionTrack)z=h.languageCode,m=h.displayName,Q=h.vssId,t=h.kind,y=h.id;l.push(new g.$H({id:e,languageCode:z,languageName:m,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:t,captionId:y}))}}return l},QeG=function(P,v,l){var e=[],h;
for(h in P.W.W)if(P.W.W.hasOwnProperty(h)){var z=P.W.W[h];if(g.Gr(z,l||null)){var m=z.info.captionTrack;m&&m.languageCode===v&&e.push(z)}}return e.length?e[0]:null},tuy=function(P,v){if(!P.V("html5_enable_sabr_live_captions")||!P.Ei()||!g.PS(P)||P.W!=null&&g.bq(v.N())&&!P.W.isManifestless&&P.W.W.rawcc!=null)return!1;
v=!!P.W&&P.W.isManifestless&&Object.values(P.W.W).some(function(l){return g.Gr(l,"386")});
P=!!P.W&&!P.W.isManifestless&&g.b0D(P.W);return v||P},aU=function(){KE.call(this)},ylj=function(P,v,l,e,h,z,m,Q,t){switch(m.tagName){case "b":Q.bold=!0;
break;case "i":Q.italic=!0;break;case "u":Q.underline=!0}for(var y=0;y<m.childNodes.length;y++){var C=m.childNodes[y];if(C.nodeType===3)C=new uR(v,l,e,h.id,C.nodeValue,z||y>0,g.pU(Q)?void 0:Q),t.push(C),h.W.push(C);else{var f={};Object.assign(f,Q);ylj(P,v,l,e,h,!0,C,f,t)}}},C5o=function(P){var v=P.split(":");
P=0;v=g.N(v);for(var l=v.next();!l.done;l=v.next())P=P*60+Number(l.value);return P*1E3},fHv=function(P,v,l,e){e=Object.assign({Z1:0},e);
return new cf(P,v,l,"_"+qY++,e)},Hf=function(P,v){g.U.call(this);
this.J=P;this.O$=v;this.W=null;this.K=this.J.tP();this.logger=new g.Rf("caps")},k9j=function(P,v,l){if(typeof v==="string"||Vpm(v))return[{trackData:v,
CQ:l}];var e=new DataView(v);if(e.byteLength<=8||e.getUint32(4)!==1718909296)return[];var h=g.KLw(e);if(P.K&&h){var z=g.wzu(h),m=g.$g7(h);h=h.lZ;z&&h&&P.K.j5(h,z,m)}P=g.eV(e,1835295092);if(!P||!P.length||!P[0].size)return[];z=[];for(m=0;m<P.length;m++)h=P[m],h=new Uint8Array(v,h.dataOffset,h.size-(h.dataOffset-h.offset)),h=g.pa(h),z.push({trackData:h,CQ:l+m*1E3});g7Y(e,z,l);return z=z.filter(function(Q){return!!Q.trackData})},g7Y=function(P,v,l){var e=g.s_(P,0,1836476516),h=9E4;
e&&(h=g.rG(e)||9E4);e=0;for(var z=g.eV(P,1836019558),m=0;m<z.length;m++){var Q=z[m];m<v.length&&(Q=g.s_(P,Q.dataOffset,1953653094))&&(Q=g.s_(P,Q.dataOffset,1952867444))&&(Q=g.vH(Q)/h*1E3,m===0&&(e=Q),v[m].CQ=Q-e+l||l*m*1E3)}},wi3=function(P){var v={};
if(P=g.n_(P))v.lang=P,g.zyy.test(P)&&(v.zJ=1);return v},Ed=function(P){g.x0.call(this,P);
var v=this;this.J=P;this.wM=[];this.J5={};this.Ic={};this.S=!1;this.Y="NONE";this.W=this.X=this.Wg=this.q5=this.U$=null;this.TG={E_:function(){v.E_()},
w2:function(z,m,Q,t){v.w2(z,m,Q,t)}};
this.K=null;this.O$=this.J.N();this.videoData=this.J.getVideoData();this.Bg=this.J.S2();var l;this.D3=(l=this.J.getVideoData(1))==null?void 0:g.VW(l);this.G={UQ:{}};this.T={UQ:{}};g.vS(this.videoData)?this.Y="OFFLINE":tuy(this.videoData,this.J)?this.Y="SABR_LIVE":g.e_y(this.videoData,this.J)?this.Y="LIVE":this.videoData.captionTracks.length?this.Y="INNERTUBE":this.videoData.t3&&(this.Y="TTS");this.h5=this.O$.controlsType==="3";this.A5=new Hf(this.J,this.O$);this.T1=new g.Z1(this);this.j=new g.O({L:"div",
D:"ytp-caption-window-container",B:{id:"ytp-caption-window-container"}});this.QW={top:0,right:0,bottom:0,left:0,width:1,height:1};l=null;var e=g.W7("yt-html5-player-modules::subtitlesModuleData");e&&(l=new g.X3(e));this.storage=l;var h;this.nI=!((h=P.ZR())==null||!h.aE());this.Z=$Vy(this);this.kf=!this.Z&&this.h5&&this.nI&&(this.Y==="LIVE"||this.Y==="SABR_LIVE");g.Z(this,this.A5);this.Z?this.Pg=this.Hg=null:(this.Hg=new g.zl(this.cO,void 0,this),g.Z(this,this.Hg),this.Pg=new g.mr(this.OXf,2E3,this),
g.Z(this,this.Pg));g.Z(this,this.T1);g.i2(this.player,this.j.element,4);g.Z(this,this.j);this.Z||this.T1.C(P,"resize",this.t7);(this.WK=g.iy(this.O$)&&!g.cx()&&!this.J.isFullscreen()&&!this.Z&&!this.kf)&&this.T1.C(P,"resize",this.VNg);this.T1.C(P,"onPlaybackAudioChange",this.hrf);this.T1.C(P,g.Ce("captions"),function(z){v.onCueRangeEnter(z)});
this.T1.C(P,g.fe("captions"),function(z){v.onCueRangeExit(z)});
this.D3&&this.T1.C(P,"videodatachange",function(z,m){v.onVideoDataChange(z,m)});
IHj(this,mTm()||{});this.player.eN("onCaptionsModuleAvailable")},NQj=function(P){if(P.O$.WK===1||P.videoData.ZX===1||g.Ac(P.videoData,"yt:cc")==="alwayson")return!0;
if(P.videoData.captionTracks.length)var v=P.getAudioTrack().K;if(P.O$.WK===2){if(g.Po(P.O$))var l=DVG(P);else if(P.storage)try{l=P.storage.get("module-enabled")}catch(h){P.storage.remove("module-enabled")}else l=null;if(l!=null)return!!l}l=TOb(P.player.getAudioTrack(),g.Po(P.O$));var e=g.Ac(P.videoData,"yt:cc");if(n7y(P)===void 0){if(l==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return e?e==="on":!0;if(l==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return e==="on"}else return e==="on";return v==="ON"||
g.Ac(P.videoData,"yt:cc")==="on"},Wf=function(P,v){if(P.K&&(v===void 0||!v)||!P.videoData.captionTracks.length)return!1;
P=P.getAudioTrack();return!!P.W||P.K==="FORCED_ON"},n7y=function(P){var v=void 0,l=g.rD(g.sY(),65);
if(g.Po(P.O$)&&l!=null){if(DVG(P)!=null)return!1;v=!l}return v},oU=function(P,v){if(!P.W)return null;
if(P.X&&P.X.Y)return P.X.Y;v=Jlm(P,v);v=g.DR(P.W.K,v);var l=null;if(Viv(P.O$)){var e=P.J.isInline()?void 0:g.au("yt-player-caption-sticky-language");for(var h=[e,P.videoData.captionsLanguagePreference,P.O$.captionsLanguagePreference,g.Ac(P.videoData,"yt:cc_default_lang")],z=!1,m=0;m<h.length;m++){var Q=h[m];if(Q){z=!0;for(var t=0;t<v.length;t++)if(g.n_(v[t])===Q)return v[t];for(t=0;t<v.length;t++)if(g.n_(v[t]).split("-")[0]===Q.split("-")[0])return v[t]}}if(z&&P.W&&(h=P.W.Z,h.length))for(h=g.N(h),
z=h.next();!z.done;z=h.next())if(z=z.value,z.languageCode===e){l=z;break}}else for(e=[P.videoData.captionsLanguagePreference,P.O$.captionsLanguagePreference,g.Ac(P.videoData,"yt:cc_default_lang")],h=0;h<e.length;h++)for(z=0;z<v.length;z++)if(g.n_(v[z])===e[h])return v[z];e=null;P.X&&P.X.G&&(e=P.X.G);e||(e=v.find(function(y){return y.isDefault})||null);
e||(e=v[0]||Od(P));e&&l&&g.n_(e).split("-")[0]!==l.languageCode.split("-")[0]&&(e=dXy(e,l));return e},Od=function(P){return P.X&&P.X.W},sd=function(P){var v=Od(P);
return!!v&&P.K===v},uDY=function(P,v){var l=P.J.ZR().YY().textTracks;
P=P.K.toString();for(var e=0;e<l.length;e++){var h=l[e];h.id===P&&(v?h.mode!=="showing"&&(h.mode="showing"):h.mode==="showing"&&(h.mode="disabled"))}},Tq=function(P,v,l){P.loaded&&P.unload();
l!=null&&(P.S=l,P.S&&(g.Po(P.O$)?rp(P,!!v):MY(P,!!v)));P.O$.V("html5_report_caption_format_change")&&KSy(P,P.K,v,P.S,!1);P.K=v;Wf(P)&&(v=Od(P),P.O$.V("html5_report_caption_format_change")&&KSy(P,P.K,v,P.S,!0),P.K=v);var e;clQ(P,(e=P.K)!=null?e:void 0);P.load()},FS3=function(P,v){if(v instanceof cf){var l=P.J5[v.id];
l&&l.K!==v&&(l.dispose(),delete P.J5[v.id],l=null);l||(l=q1x(P,v))&&(P.J5[v.id]=l)}else l=v.windowId,P.Ic[l]||(P.Ic[l]=[]),P.Ic[l].push(v)},q1x=function(P,v){var l=AlA(P);
if(!l)return null;var e=P.K?g.n_(P.K):null;e&&g.zyy.test(e)&&(v.params.zJ=1);var h=P.Bg.getPlayerSize();e=h.height*P.QW.height;h=h.width*P.QW.width;P.O$.playerStyle!=="google-live"||P.G.isDefault||Object.assign(v.params,P.G);switch(v.params.Z1!=null?v.params.Z1:v.W.length>1?1:0){case 1:return new Xb(v,P.G,P.T,l.width,l.height,h,e,P.O$.experiments,P.En.bind(P),P.J);case 2:return new j7(v,P.G,P.T,l.width,l.height,h,e,P.O$.experiments,P.En.bind(P),P.J);default:return new gp(v,P.G,P.T,l.width,l.height,
h,e,P.O$.experiments,P.En.bind(P),P.J)}},IHj=function(P,v,l){l=l===void 0?!1:l;
var e=Vb.UQ;P.G={};Object.assign(P.G,Vb);P.G.UQ={};Object.assign(P.G.UQ,e);P.T={UQ:{}};var h=v.backgroundOverride?P.T:P.G,z=v.background||e.background;xn.test(z);h.UQ.background=z;h=v.colorOverride?P.T:P.G;z=v.color||e.color;xn.test(z);h.UQ.color=z;h=v.windowColorOverride?P.T:P.G;z=v.windowColor||Vb.windowColor;xn.test(z);h.windowColor=z;h=v.backgroundOpacityOverride?P.T:P.G;z=v.backgroundOpacity;z==null&&(z=e.backgroundOpacity);h.UQ.backgroundOpacity=z;h=v.fontSizeIncrementOverride?P.T:P.G;z=v.fontSizeIncrement;
z==null&&(z=e.fontSizeIncrement);h.UQ.fontSizeIncrement=z;z=v.fontStyleOverride?P.T:P.G;h=v.fontStyle;h==null&&(h=e.bold&&e.italic?3:e.bold?1:e.italic?2:0);z=z.UQ;switch(h){case 1:z.bold=!0;delete z.italic;break;case 2:delete z.bold;z.italic=!0;break;case 3:z.bold=!0;z.italic=!0;break;default:delete z.bold,delete z.italic}h=v.textOpacityOverride?P.T:P.G;z=v.textOpacity;z==null&&(z=e.textOpacity);h.UQ.textOpacity=z;h=v.windowOpacityOverride?P.T:P.G;z=v.windowOpacity;z==null&&(z=Vb.windowOpacity);h.windowOpacity=
z;h=v.charEdgeStyleOverride?P.T:P.G;z=v.charEdgeStyle;z==null&&(z=e.charEdgeStyle);h.UQ.charEdgeStyle=z;h=v.fontFamilyOverride?P.T:P.G;z=v.fontFamily;z==null&&(z=e.fontFamily);h.UQ.fontFamily=z;P.loaded&&P.t7();l&&g.jB("yt-player-caption-display-settings",v,2592E3)},Y1x=function(P,v){if(!P.W)return{};
if(v){P.O$.V("html5_report_caption_format_intent")&&!g.pU(v)&&P.H9(v.vss_id,"m");if(P.Z||!g.Oy(v))return;if(g.pU(v)){Tq(P,null,!0);return}for(var l,e=g.DR(P.W.K,!0),h=0;h<e.length;h++){var z=e[h];z.languageCode!==v.languageCode||l&&(z.languageName!==v.languageName||(z.captionId||"")!==(v.captionId||"")||g.II(z)!==v.displayName)||(l=v.translationLanguage?dXy(z,v.translationLanguage):z)}P.BX(v.position);!l||l===P.K&&P.loaded||(v=g.Og(),e=g.n_(l),v.length&&e===v[v.length-1]||(v.push(e),g.jB("yt-player-caption-language-preferences",
v)),Viv(P.O$)&&!P.J.isInline()&&g.jB("yt-player-caption-sticky-language",e,2592E3),Tq(P,l,!0))}else return P.loaded&&P.K&&!sd(P)?g.Dv(P.K):{};return""},xVj=function(P,v,l){v&&!P.Wg?(v=OUd({zJ:0,
lang:"en"}),P.Wg=[v,new uR(v.start,v.end-v.start,0,v.id,l!=null?l:"Captions look like this")],P.player.iC(P.Wg)):!v&&P.Wg&&(bSy(P,P.Wg),P.Wg=null)},bSy=function(P,v){P.player.j6(v);
v=g.N(v);for(var l=v.next();!l.done;l=v.next())g.Tv(P.wM,l.value);yb(P.Hg)},clQ=function(P,v){P.O$.V("html5_modify_caption_vss_logging")&&(P.videoData.e0=v)},AlA=function(P){var v=P.Bg.getVideoContentRect(!0).height,l=P.Bg.getVideoContentRect(!0).width;
if(!v||!l)return null;v*=P.QW.height;l*=P.QW.width;return{width:l,height:v}},MY=function(P,v){if(P.storage)try{P.storage.set("module-enabled",v)}catch(l){}},rp=function(P,v){P.J.isInline()||g.jB("yt-player-sticky-caption",v,2592E3)},DVG=function(P){if(!P.J.isInline())return g.au("yt-player-sticky-caption")},$Vy=function(P){var v,l=!((v=P.J.ZR())==null||!v.Tz());
return P.h5&&l&&P.Y!=="LIVE"&&P.Y!=="SABR_LIVE"},Jlm=function(P,v){g.jr(P.videoData)&&(v=!0);
v||(v=P.Y==="TTS"?!1:P.Y==="INNERTUBE"?!1:!0);return v||P.O$.V("web_deprecate_always_includes_asr_setting")&&g.Po(P.O$)?!0:!!g.rD(g.sY(),66)},KSy=function(P,v,l,e,h){h?P.uh(l,!0,"g"):e?v?P.uh(l,!!l,"m"):l&&P.uh(l,!0,"m"):!v&&l&&P.uh(l,!0,"s")};
g.LX.prototype.Pc=g.e9(66,function(){return!1});
g.LX.prototype.Rq=g.e9(65,function(){});
g.S_.prototype.Rq=g.e9(64,function(P,v,l){var e=this;this.s$();v=this.o2(P,v);var h=this.j2.N().V("html5_report_captions_ctmp_qoe"),z=(0,g.Gz)();this.Op();MiG(this,v,{format:"RAW",onSuccess:function(m){e.W=null;if(h){var Q=(m.responseText.length/1024).toFixed(),t=(0,g.Gz)();e.videoData.f0("capresp",{ms:t-z,kb:Q})}l.w2(m.responseText,P)},
onError:h?function(m){var Q;m=(Q=m==null?void 0:m.status)!=null?Q:0;e.videoData.f0("capfail",{status:m})}:void 0,
withCredentials:!0})});
g.X0.prototype.Rq=g.e9(63,function(P,v,l){var e=this;this.s$();v=this.o2(P,v);this.Op();this.W=g.SN(v,{format:"RAW",onSuccess:function(h){e.W=null;l.w2(h.responseText,P)},
withCredentials:!0})});
g.CX.prototype.rZ=g.e9(62,function(){for(var P=g.rY(document,"track",void 0,this.W),v=0;v<P.length;v++)g.Re(P[v])});
g.E4.prototype.rZ=g.e9(61,function(){this.mediaElement.rZ()});
g.CX.prototype.aE=g.e9(60,function(){return!(!this.W.textTracks||!this.W.textTracks.addEventListener)});
g.E4.prototype.aE=g.e9(59,function(){return this.mediaElement.aE()});
g.CX.prototype.Tz=g.e9(58,function(){return!!this.W.textTracks});
g.E4.prototype.Tz=g.e9(57,function(){return this.mediaElement.Tz()});
g.CX.prototype.Mu=g.e9(56,function(P){for(var v=0;v<P.length;v++)this.W.appendChild(P[v])});
g.E4.prototype.Mu=g.e9(55,function(P){this.mediaElement.Mu(P)});
g.wT.prototype.j5=g.e9(50,function(P,v,l){this.PR.j5(P,v,l)});
g.dC.prototype.j5=g.e9(49,function(P,v,l){this.Pg.set(P,{Z$:v,T7:l})});
g.wT.prototype.Jz=g.e9(48,function(P){return this.PR.Jz(P)});
g.dC.prototype.Jz=g.e9(47,function(P){var v=2;this.T.has(P)?v=0:g.UY2(this,P)&&(v=1);return v});
g.Rf.prototype.W=g.e9(46,function(P){g.QJ.apply(null,[5,this.tag,P].concat(g.u(g.bD.apply(1,arguments))))});
g.b2.prototype.Ap=g.e9(43,function(P){var v=g.JM(this.app);return v?v.Ap(P):!1});
g.V4.prototype.Ap=g.e9(42,function(P){return this.LY().some(function(v){return v.namespace===P})});
g.dT.prototype.Ap=g.e9(41,function(P){return this.M5.ih.Ap(P)});
g.b2.prototype.H9=g.e9(39,function(P,v){var l;(l=this.app.yW())==null||l.H9(P,v)});
g.G5.prototype.H9=g.e9(38,function(P,v){P=[P,v];g.Sh(this,g.b7(this.provider),"cfi",P)});
g.rT.prototype.H9=g.e9(37,function(P,v){this.qoe&&this.qoe.H9(P,v)});
g.dT.prototype.H9=g.e9(36,function(P,v){this.M5.H9(P,v)});
g.uj.prototype.H9=g.e9(35,function(P,v){this.uQ().H9(P,v)});
g.b2.prototype.uh=g.e9(34,function(P,v,l){var e;(e=this.app.yW())==null||e.uh(P,v,l)});
g.G5.prototype.uh=g.e9(33,function(P,v,l){if(this.Hg!==P||this.CI!==v)v=v==="rawcc"?"":v,l=[P,v,this.Hg,l],g.Sh(this,g.b7(this.provider),"cfs",l),this.Hg=P,this.CI=v});
g.rT.prototype.uh=g.e9(32,function(P,v,l){this.qoe&&this.qoe.uh(P,v,l)});
g.dT.prototype.uh=g.e9(31,function(P,v,l){this.M5.uh(P,v,l)});
g.uj.prototype.uh=g.e9(30,function(P,v,l){this.uQ().uh(P,v,l)});
g.Cf.prototype.v8=g.e9(19,function(){return this.S});
g.Km.prototype.v8=g.e9(18,function(){var P;return((P=this.yW())==null?void 0:P.tP())||null});
g.b2.prototype.tP=g.e9(17,function(){return this.app.v8()});
g.dT.prototype.tP=g.e9(16,function(){return this.M5.tP()});
g.uj.prototype.tP=g.e9(15,function(){var P;return((P=this.K0)==null?void 0:P.v8())||null});
g.SM.prototype.w$=g.e9(1,function(P){return(P=this.OU(P))?P.K:0});
g.RK.prototype.w$=g.e9(0,function(){return 0});
var efj=/#(.)(.)(.)/,lco=/^#(?:[0-9a-f]{3}){1,2}$/i,C6x={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};CE.prototype.contains=function(P){P=g.R4(this.segments,P);return P>=0||P<0&&(-P-1)%2===1};
CE.prototype.length=function(){return this.segments.length/2};
g.D(Qvj,g.U);g.R=Qvj.prototype;g.R.G1=function(){g.U.prototype.G1.call(this);this.G&&this.G.cancel()};
g.R.nx=function(){this.seekTo(this.player.getCurrentTime())};
g.R.seekTo=function(P){P-=this.player.fh();var v=this.W;this.W=g.WA(this.Wg.wW(P).N5);v!==this.W&&this.X&&this.X()};
g.R.reset=function(){this.Y=new CE;this.T=-1;this.G&&(this.G.cancel(),this.G=null)};
g.R.T0=function(){this.s$();var P;if(P=this.W!=null)P=this.W,P=P.W.Ss(P);if(P&&!this.G&&!(this.W&&this.W.startTime-this.player.getCurrentTime()>30)){P=this.W;P=P.W.Ql(P);var v=P.N5[0],l;if((l=this.player.getVideoData())==null?0:l.enableServerStitchedDai)if(l=this.player.tP()){var e=v.W.info.id,h=v.n0,z=P.N5[0].ao;if(this.policy.Hg){if(l=l.m7(z,h,e,3))P.Y=l}else if(e=l.gZ(z,h,e,3))if(l=l.Jz(h),l===0)e&&(P.W=new g.q9(e));else if(l===2){this.j.start();tpv(this)&&this.seekTo(this.player.getCurrentTime());
return}}v.W.index.Zh(v.n0)?(this.Y.contains(P.N5[0].n0)||y3o(this,P),this.W=g.WA(P.N5)):tpv(this)&&this.seekTo(this.player.getCurrentTime())}this.j.start()};
g.D(fE,g.LX);g.R=fE.prototype;g.R.Rq=function(P,v,l){var e=this;this.Op();v=grm(this,P.getId());v||(v=P.languageCode,v=this.W.isManifestless?kAo(this,v,"386"):kAo(this,v));if(v){var h=(v.index.w$(v.index.EW())-v.index.getStartTime(v.index.EW()))*1E3,z=this.J.N(),m=new g.iqx(z),Q=function(){e.G&&e.G.reset();e.T=!0};
z.V("html5_keep_caption_data_after_seek")&&(Q=null);this.G=new Qvj(m,this.J,v,function(t,y){l.w2(t,P,y,h)},this.j||g.PB(v.info),Q)}};
g.R.Pc=function(){var P=this.T;this.T=!1;return P};
g.R.P1=function(P){var v=this.J.N().V("html5_fallback_if_rawcc_missing");var l=this.W.W.rawcc!=null;if(!this.j||!l&&v)v=this.W.isManifestless?fc1(this,"386"):fc1(this);else{if(!l){this.logger.W(386248249,"rawcc used but unavailable");return}v=[new g.$H({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.$H({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}v=g.N(v);
for(l=v.next();!l.done;l=v.next())g.pX(this.K,l.value);P.E_()};
g.R.Op=function(){this.G&&(this.G.dispose(),this.G=null)};
g.R.o2=function(){return""};
g.R.Ef=function(){this.G&&(this.G.reset(),this.J.Pz("captions"))};
var xn=/^#(?:[0-9a-f]{3}){1,2}$/i;var Icj=["left","right","center","justify"];g.D(gp,g.O);g.R=gp.prototype;g.R.s8=function(P,v){this.A5=P;this.D3=v;var l=g.pn(this.element,this.element.parentElement);this.U$=P-l.x;this.Bg=v-l.y};
g.R.Hn=function(P,v){if(P!==this.A5||v!==this.D3){g.gt(this.element,"ytp-dragging")||g.kk(this.element,"ytp-dragging");var l=g.S8(this.element);P=P-this.U$-.02*this.playerWidth;var e=v-this.Bg-.02*this.playerHeight,h=(P+l.width/2)/this.maxWidth*3;h=Math.floor(g.CU(h,0,2));var z=(e+l.height/2)/this.maxHeight*3;z=Math.floor(g.CU(z,0,2));v=h+z*3;P=(P+h/2*l.width)/this.maxWidth;P=g.CU(P,0,1)*100;l=(e+z/2*l.height)/this.maxHeight;l=g.CU(l,0,1)*100;this.K.params.Nj=v;this.K.params.X6=l;this.K.params.aK=
P;this.K.params.isDefault=!1;this.W.Nj=v;this.W.X6=l;this.W.aK=P;this.W.isDefault=!1;this.QW.Nj=v;this.QW.X6=l;this.QW.aK=P;this.QW.isDefault=!1;this.wA()}};
g.R.tG=function(){g.$k(this.element,"ytp-dragging")};
g.R.wA=function(){this.Wy(this.j)};
g.R.getType=function(){return this.type};
g.R.Wy=function(P){var v=this.WK?0:Math.min(this.s9(),this.maxWidth),l=this.HH(),e=this.WK;if(e){var h=getComputedStyle(this.Y.parentNode);h=kn(h.borderLeftWidth)+kn(h.borderRightWidth)+kn(h.paddingLeft)+kn(h.paddingRight)}else h=0;var z=h;h="";this.K.params.zJ===3&&(h="rotate(180deg)");var m=e?"calc(96% - "+z+"px)":"96%";g.DO(this.element,{top:0,left:0,right:"",bottom:"",width:v?v+"px":"",height:l?l+"px":"","max-width":m,"max-height":m,margin:"",transform:""});this.Tp(P);h={transform:h,top:"",left:"",
width:v?v+"px":"",height:l?l+"px":"","max-width":"","max-height":""};var Q=this.W.aK*.96+2;m=this.W.Nj;switch(m){case 0:case 3:case 6:(e=this.W.UQ.fontSizeIncrement)&&e>0&&this.W.zJ!==2&&this.W.zJ!==3&&(Q=Math.max(Q/(1+e*2),2));h.left=Q+"%";break;case 1:case 4:case 7:h.left=Q+"%";Q=this.Y.offsetWidth;v||Q?(v=v||Q+1,h.width=v+"px",h["margin-left"]=e?v/-2-z/2+"px":v/-2+"px"):h.transform+=" translateX(-50%)";break;case 2:case 5:case 8:h.right=100-Q+"%"}e=this.W.X6*.96+2;switch(m){case 0:case 1:case 2:h.top=
e+"%";break;case 3:case 4:case 5:h.top=e+"%";(l=l||this.element.clientHeight)?(h.height=l+"px",h["margin-top"]=l/-2+"px"):h.transform+=" translateY(-50%)";break;case 6:case 7:case 8:h.bottom=100-e+"%"}g.DO(this.element,h);if(this.T){l=this.Y.offsetHeight;e=1;for(v=0;v<P.length;v++)h=P[v],typeof h.text==="string"&&(e+=h.text.split("\n").length-1,h.append||v===0||e++);l/=e;this.T.style.height=l+"px";this.T.style.width=l+"px";this.element.style.paddingLeft=l+5+"px";this.element.style.paddingRight=l+
5+"px";P=Number(this.element.style.marginLeft.replace("px",""))-l-5;l=Number(this.element.style.marginRight.replace("px",""))-l-5;this.element.style.marginLeft=P+"px";this.element.style.marginRight=l+"px"}};
g.R.Tp=function(P){var v;for(v=0;v<P.length&&P[v]===this.j[v];v++);if(this.kf||this.j.length>v)v=0,this.kf=!1,this.j=[],this.S=this.Hg=this.wM=null,g.z9(this.Y);for(;v<P.length;v++)uNv(this,P[v])};
g.R.s9=function(){return 0};
g.R.HH=function(){return 0};
g.R.toString=function(){return g.O.prototype.toString.call(this)};c3d.prototype.clear=function(){this.G=this.time=this.mode=0;this.W=[];this.reset()};
c3d.prototype.reset=function(){this.mode=0;this.Y.reset(0);this.Z.reset(1)};
var qqA=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];wp.prototype.set=function(P){this.type=P};
wp.prototype.get=function(){return this.type};
$n.prototype.clear=function(){this.state=0};
$n.prototype.update=function(){this.state=this.state===2?1:0};
$n.prototype.n6=function(){return this.state!==0};
$n.prototype.matches=function(P,v){return this.n6()&&P===this.Om&&v===this.MR};
xTo.prototype.reset=function(){this.timestamp=this.W=0};
IU.prototype.updateTime=function(P){for(var v=1;v<=15;++v)for(var l=1;l<=32;++l)this.G[v][l].timestamp=P};
IU.prototype.debugString=function(){for(var P="\n",v=1;v<=15;++v){for(var l=1;l<=32;++l){var e=this.G[v][l];P=e.W===0?P+"_":P+String.fromCharCode(e.W)}P+="\n"}return P};
IU.prototype.reset=function(P){for(var v=0;v<=15;v++)for(var l=0;l<=32;l++)this.G[v][l].reset();this.Y=P;this.W=0;this.K=this.row=1};
var prx=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Ltb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Sqy=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],GAy=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];UTb.prototype.reset=function(P,v){this.Z=v;this.style.set(2);this.K=this.T;this.Y=this.j;this.W=this.K;var l=(P<<2)+(v<<1);this.T.reset(l);this.j.reset(l);this.text.reset((P<<2)+(v<<1)+1)};
KtY.prototype.reset=function(P){this.Z=P;this.K.clear();this.Y=this.G;this.G.reset(P,0);this.T.reset(P,1)};HUj.prototype.Y=function(){};g.D(uR,g.tn);uR.prototype.toString=function(){return g.tn.prototype.toString.call(this)};g.D(KE,g.U);KE.prototype.Rw=function(){return[]};
KE.prototype.reset=function(){};g.D(cf,g.tn);cf.prototype.toString=function(){return g.tn.prototype.toString.call(this)};
var qY=0;g.D(Fb,KE);Fb.prototype.reset=function(){this.T={};this.K=this.W=null;this.Z=!0};
Fb.prototype.Rw=function(P,v){P=P.firstChild;P.getAttribute("format");v=v||0;Number.isFinite(v);P=Array.from(P.childNodes);P=g.N(P);for(var l=P.next();!l.done;l=P.next())if(l=l.value,l.nodeType===1)switch(l.tagName){case "head":var e=l;break;case "body":var h=l}if(e)for(e=Array.from(e.childNodes),e=g.N(e),P=e.next();!P.done;P=e.next())if(P=P.value,P.nodeType===1)switch(P.tagName){case "pen":l=P.getAttribute("id");var z=this.pens,m={},Q=P.getAttribute("p");Q&&Object.assign(m,this.pens[Q]);Q=Yn(P,"b");
Q!=null&&(m.bold=Q);Q=Yn(P,"i");Q!=null&&(m.italic=Q);Q=Yn(P,"u");Q!=null&&(m.underline=Q);Q=bR(P,"et");Q!=null&&(m.charEdgeStyle=Q);Q=bR(P,"of");Q!=null&&(m.offset=Q);Q=pE(P,"bc");Q!=null&&(m.background=Q);Q=pE(P,"ec");Q!=null&&(m.IW=Q);Q=pE(P,"fc");Q!=null&&(m.color=Q);Q=bR(P,"fs");Q!=null&&Q!==0&&(m.fontFamily=Q);Q=Ah(P,"sz");Q!==void 0&&(m.fontSizeIncrement=Q/100-1);Q=Ah(P,"bo");Q!==void 0&&(m.backgroundOpacity=Q/255);Q=Ah(P,"fo");Q!==void 0&&(m.textOpacity=Q/255);Q=bR(P,"rb");Q!=null&&Q!==10&&
Q!==0&&(m.GW=Q>10?Q-1:Q);P=bR(P,"hg");P!=null&&(m.zf=P);z[l]=m;break;case "ws":l=P.getAttribute("id");this.S[l]=oro(this,P);break;case "wp":l=P.getAttribute("id"),this.j[l]=sv3(this,P)}if(h){e=[];h=Array.from(h.childNodes);h=g.N(h);for(P=h.next();!P.done;P=h.next())if(P=P.value,P.nodeType===1)switch(P.tagName){case "w":this.W=r3A(this,P,v,!1);(P=this.T[this.W.id])&&P.end>this.W.start&&(P.end=this.W.start);this.T[this.W.id]=this.W;e.push(this.W);break;case "p":var t=P;Q=v;l=[];z=t.getAttribute("w")||
this.Y;m=!!Yn(t,"a");Q=(Ah(t,"t")||0)+Q;var y=Ah(t,"d")||5E3;m||(!this.Z&&this.K&&this.K.windowId===z&&this.K.end>Q&&(this.K.end=Q),this.K&&this.K.text==="\n"&&(this.K.text=""));var C=m?6:5,f=t.getAttribute("p");f=f?this.pens[f]:null;var k=Array.from(t.childNodes);k.length&&(this.Z=t.getAttribute("d")!=null);for(t=0;t<k.length;t++){var w=k[t],I=void 0;t>0&&(m=!0);var J=void 0;w.nodeType===1&&(J=w);if(J&&J.tagName==="s"){if((w=(w=J.getAttribute("p"))?this.pens[w]:null)&&w.GW&&(w.GW===1?(w=k.slice(t,
t+4),w.length===4&&(I=Wto(Q,y,z,m,C,w,this.pens),t+=3)):I=Wto(Q,y,z,m,C,[J],this.pens)),!I){var K=J;I=Q;J=y;w=z;var q=m,A=C,x=K.textContent?K.textContent:"",S=K.getAttribute("p");S=S?this.pens[S]:null;K=Ah(K,"t")||0;I=new uR(I+K,J-K,A,w,x,q,S)}}else I=new uR(Q,y,C,z,w.textContent||"",m,f);l.push(I);this.K=I}if(l.length>0)for(l[0].windowId===this.Y&&(this.W=r3A(this,P,v,!0),e.push(this.W)),P=g.N(l),l=P.next();!l.done;l=P.next())l=l.value,l.windowId=this.W.id,this.W.W.push(l),e.push(l)}v=e}else v=[];
return v};var piA=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.D(LE,KE);LE.prototype.reset=function(){this.K.clear()};
LE.prototype.Rw=function(P,v){var l=JSON.parse(P);if(!l)return[];if(l.pens){P=0;for(var e=g.N(l.pens),h=e.next();!h.done;h=e.next()){h=h.value;var z={},m=h.pParentId;m&&Object.assign(z,this.W.get(m));h.bAttr&&(z.bold=!0);h.iAttr&&(z.italic=!0);h.uAttr&&(z.underline=!0);m=h.ofOffset;m!=null&&(z.offset=m);h.szPenSize!==void 0&&(z.fontSizeIncrement=h.szPenSize/100-1);m=h.etEdgeType;m!=null&&(z.charEdgeStyle=m);h.ecEdgeColor!==void 0&&(z.IW=S7(h.ecEdgeColor));m=h.fsFontStyle;m!=null&&m!==0&&(z.fontFamily=
m);h.fcForeColor!==void 0&&(z.color=S7(h.fcForeColor));h.foForeAlpha!==void 0&&(z.textOpacity=h.foForeAlpha/255);h.bcBackColor!==void 0&&(z.background=S7(h.bcBackColor));h.boBackAlpha!==void 0&&(z.backgroundOpacity=h.boBackAlpha/255);(m=h.rbRuby)&&m!==10&&(z.GW=m>10?m-1:m,z.Bi=piA.get(z.GW));h.hgHorizGroup&&(z.zf=h.hgHorizGroup);this.W.set(P++,z)}}if(l.wsWinStyles)for(P=0,e=g.N(l.wsWinStyles),h=e.next();!h.done;h=e.next())h=h.value,z={},(m=h.wsParentId)?Object.assign(z,this.Y.get(m)):Object.assign(z,
this.Z),h.mhModeHint!==void 0&&(z.Z1=h.mhModeHint),h.juJustifCode!==void 0&&(z.textAlign=h.juJustifCode),h.pdPrintDir!==void 0&&(z.zJ=h.pdPrintDir),h.sdScrollDir!==void 0&&(z.gy=h.sdScrollDir),h.wfcWinFillColor!==void 0&&(z.windowColor=S7(h.wfcWinFillColor)),h.wfoWinFillAlpha!==void 0&&(z.windowOpacity=h.wfoWinFillAlpha/255),this.Y.set(P++,z);if(l.wpWinPositions)for(P=0,e=g.N(l.wpWinPositions),h=e.next();!h.done;h=e.next())h=h.value,z={},(m=h.wpParentId)&&Object.assign(z,this.G.get(m)),h.ahHorPos!==
void 0&&(z.aK=h.ahHorPos),h.apPoint!==void 0&&(z.Nj=h.apPoint),h.avVerPos!==void 0&&(z.X6=h.avVerPos),h.ccCols!==void 0&&(z.Kl=h.ccCols),h.rcRows!==void 0&&(z.Ta=h.rcRows),this.G.set(P++,z);if(l.events){P=[];l=g.N(l.events);for(e=l.next();!e.done;e=l.next()){var Q=e.value;h=(Q.tStartMs||0)+v;z=Q.dDurationMs||0;if(Q.id)m=String(Q.id),e=Mpm(this,Q,h,z,m),P.push(e),this.K.set(m,e);else{Q.wWinId?m=Q.wWinId.toString():(m="_"+qY++,e=Mpm(this,Q,h,z,m),P.push(e),this.K.set(m,e));e=P;var t=Q;z===0&&(z=5E3);
Q=this.K.get(m);var y=!!t.aAppend,C=y?6:5,f=t.segs,k=null;t.pPenId&&(k=this.W.get(t.pPenId));for(t=0;t<f.length;t++){var w=f[t],I=w.utf8;if(I){var J=w.tOffsetMs||0,K=null;w.pPenId&&(K=this.W.get(w.pPenId));if((Q.params.Z1!=null?Q.params.Z1:Q.W.length>1?1:0)===2&&y&&I==="\n")continue;w=null;var q=[],A;if(A=K&&K.GW===1){A=f;var x=t;if(x+3>=A.length||!A[x+1].pPenId||!A[x+2].pPenId||!A[x+3].pPenId)A=!1;else{var S=A[x+1].pPenId;(S=this.W.get(S))&&S.GW&&S.GW===2?(S=A[x+2].pPenId,S=this.W.get(S),!S||!S.GW||
S.GW<3?A=!1:(S=A[x+3].pPenId,A=(S=this.W.get(S))&&S.GW&&S.GW===2?!0:!1)):A=!1}}if(A)J=f[t+1].utf8,w=f[t+3].utf8,A=f[t+2].utf8,x=this.W.get(f[t+2].pPenId),I=Erj(I,J,A,w,x),w=new uR(h,z,C,m,I,y,K),t+=3;else{if(I.indexOf("<")>-1){var B=void 0;q=K;A=k;x=h;S=z;var E=J,r=C,hq=y,R7=[],Pw=g.V2("<html>"+I+"</html>");if(!Pw.getElementsByTagName("parsererror").length&&((B=Pw.firstChild)==null?0:B.childNodes.length))for(B=g.N(Pw.firstChild.childNodes),Pw=B.next();!Pw.done;Pw=B.next()){Pw=Pw.value;var H=void 0,
T=void 0,n=(T=(H=Pw.textContent)==null?void 0:H.replace(/\n/g,""))!=null?T:"";if(Pw.nodeType!==3||n&&n.match(/^ *$/)==null){H={};Object.assign(H,q||A);T=void 0;switch((T=Pw)==null?void 0:T.tagName){case "b":H.bold=!0;break;case "i":H.italic=!0;break;case "u":H.underline=!0}R7.push(new uR(x+E,S-E,r,Q.id,n,hq,H))}}q=R7}q.length||(q=[new uR(h+J,z-J,C,Q.id,I,y,K||k)])}if(q.length)for(y=g.N(q),K=y.next();!K.done;K=y.next())K=K.value,e.push(K),Q.W.push(K);else w&&(e.push(w),Q.W.push(w))}y=!0}}}v=P}else v=
[];return v};g.D(Gq,g.LX);Gq.prototype.Rq=function(P,v,l){vry(this.videoData.videoId,P.vssId,l.w2)};
Gq.prototype.P1=function(P){if(this.audioTrack)for(var v=g.N(this.audioTrack.captionTracks),l=v.next();!l.done;l=v.next())g.pX(this.K,l.value);P.E_()};g.D(Xb,gp);Xb.prototype.Tp=function(P){var v=this.K.W;gp.prototype.Tp.call(this,P);for(P=P.length;P<v.length;P++){var l=v[P];if(z&&l.W===h)var e=z;else{e={};Object.assign(e,l.W);Object.assign(e,LSy);var h=l.W;var z=e}uNv(this,l,e)}};
var LSy={Ef$:!0};g.D(Bf,HUj);Bf.prototype.Y=function(P,v,l,e,h){if(l<e){var z="_"+qY++;l=l/1E3-this.T;e=e/1E3-this.T;P=new cf(l,e-l,5,z,{textAlign:0,Nj:0,aK:v*2.5,X6:P*5.33});h=new uR(l,e-l,5,z,h);this.K.push(P);this.K.push(h)}};
g.D(Z8,KE);Z8.prototype.Rw=function(P){P=new Bf(P,P.byteLength,this.K);if(TYj(P)){for(;P.byteOffset<P.W.byteLength;)for(P.version===0?P.G=Ud(P)*(1E3/45):P.version===1&&(P.G=Ud(P)*4294967296+Ud(P)),P.Z=iR(P);P.Z>0;P.Z--){var v=iR(P),l=iR(P),e=iR(P);v&4&&(v&3)===this.track&&(this.track===0||this.track===1)&&(v=this.W,v.W.push({time:P.G,type:this.track,p_:l,kN:e,order:v.W.length}))}bUx(this.W,P);return P.K}return[]};
Z8.prototype.reset=function(){this.W.clear()};g.D(j7,gp);g.R=j7.prototype;g.R.wA=function(){g.QD(this.Ic)};
g.R.aRc=function(){g.$k(this.element,"ytp-rollup-mode");this.Wy(this.It,!0)};
g.R.HH=function(){return this.G?this.Wg:this.X};
g.R.s9=function(){return this.G?this.X:this.Wg};
g.R.Wy=function(P,v){this.It=P;if(this.K.params.Ta){for(var l=0,e=0;e<this.j.length&&l<P.length;e++)this.j[e]===P[l]&&l++;l>0&&l<P.length&&(P=this.j.concat(P.slice(l)));this.TG=this.Wg;this.X=this.Wg=0;gp.prototype.Wy.call(this,P);v7x(this,v)}gp.prototype.Wy.call(this,P)};lHd.prototype.unload=function(){this.Hh!=null&&(this.J.removeEventListener("sabrCaptionsDataLoaded",this.Hh),this.Hh=null);this.hR=[];this.J.publish("sabrCaptionsBufferedRangesUpdated",this.hR)};
lHd.prototype.s1=function(P){return{formatId:g.es(P.info.W.info,this.Ei),n0:P.info.n0+(this.Ei?0:1),startTimeMs:P.info.ao*1E3,durationMs:P.info.T*1E3}};g.D(mVy,g.LX);g.R=mVy.prototype;g.R.Rq=function(P,v,l){this.Op();v=P.getId();v=v!=null&&v in this.W.W?this.W.W[v]:null;v||(v=P.languageCode,v=this.W.isManifestless?QeG(this,v,"386"):QeG(this,v));v&&(this.G=P,this.T=v,zg3(this.j,l),this.J.publish("sabrCaptionsTrackChanged",g.es(v.info,this.W.Ei)))};
g.R.P1=function(P){var v=this.W.isManifestless?Rgx(this,"386"):Rgx(this);v=g.N(v);for(var l=v.next();!l.done;l=v.next())g.pX(this.K,l.value);P.E_()};
g.R.Op=function(){this.G&&(this.G=this.T=null,this.j.unload(),this.J.publish("sabrCaptionsTrackChanged",null))};
g.R.o2=function(){return""};
g.R.Ef=function(){this.J.Pz("captions")};g.D(aU,KE);
aU.prototype.Rw=function(P,v){var l=[];P=P.split(S1y);for(var e=1;e<P.length;e++){var h=P[e],z=v;if(h!==""&&!G9b.test(h)){var m=Xij.exec(h);if(m&&m.length>=4){var Q=C5o(m[1]),t=C5o(m[2])-Q;Q+=z;var y=(m=m[3])?m.split(" "):[];m={};var C=null;var f="";var k=null,w="";y=g.N(y);for(var I=y.next();!I.done;I=y.next())if(I=I.value.split(":"),I.length===2){var J=I[1];switch(I[0]){case "line":I=J.split(",");I[0].endsWith("%")&&(C=I[0],m.X6=Number.parseInt(C,10),I.length===2&&(f=I[1].trim()));break;case "position":I=
J.split(",");k=I[0];m.aK=Number.parseInt(k,10);I.length===2&&(w=I[1].trim());break;case "align":switch(J){case "start":m.textAlign=0;break;case "middle":m.textAlign=2;break;case "end":m.textAlign=1}}}C||f||(f="end");if(!k)switch(m.textAlign){case 0:m.aK=0;break;case 1:m.aK=100;break;case 2:m.aK=50}if(m.textAlign!=null){C=0;switch(f){case "center":C+=3;break;case "end":C+=6;break;default:C+=0}switch(w){case "line-left":C+=0;break;case "center":C+=1;break;case "line-right":C+=2;break;default:switch(m.textAlign){case 0:C+=
0;break;case 2:C+=1;break;case 1:C+=2}}f=C<0||C>8?7:C;m.Nj=f}h=h.substring(Xij.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=m;m=h;h={};if(m.indexOf("<")<0&&m.indexOf("&")<0)z=fHv(Q,t,5,w),t=new uR(Q,t,5,z.id,m,!1,g.pU(h)?void 0:h),l.push(z),l.push(t),z.W.push(t);else for(f=m.split(BQb),f.length===1?(m=5,w=fHv(Q,t,m,w)):(C=m=6,w=Object.assign({Kl:32},w),w=new cf(Q,t,C,"_"+qY++,w)),l.push(w),C=Q,k=0;k<f.length;k++)y=f[k],k%2===0?(I=g.V2("<html>"+y+"</html>"),I.getElementsByTagName("parsererror").length?
(J=I.createElement("span"),J.appendChild(I.createTextNode(y))):J=I.firstChild,ylj(this,C,t-(C-Q),m,w,k>0,J,h,l)):C=C5o(y)+z}Xij.lastIndex=0}}return l};
var G9b=/^NOTE/,S1y=/(?:\r\n|\r|\n){2,}/,Xij=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),BQb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.Wg.SJ(aU,{Rw:"wvppt"});g.D(Hf,g.U);
Hf.prototype.Rw=function(P,v,l,e){e=e||0;l=k9j(this,P,l||0);P=[];try{for(var h=g.N(l),z=h.next();!z.done;z=h.next()){var m=z.value,Q=m.trackData,t=m.CQ;if(typeof Q!=="string"){l=P;var y=l.concat,C=v,f=Q,k=t,w=e;if(!Vpm(f))throw Error("Invalid binary caption track data");this.W||(this.W=new Z8(w,C));var I=this.W.Rw(f,k);var J=y.call(l,I)}else{if(Q.substring(0,6)==="WEBVTT"){l=P;var K=l.concat;this.W||(this.W=new aU);var q=this.W.Rw(Q,t);Math.random()<.01&&g.j4(Error("Deprecated subtitles format in web player: WebVTT"));var A=
K.call(l,q)}else{l=P;var x=l.concat;a:{C=v;if(Q[0]==="{")try{this.W||(this.W=new LE(wi3(C)));var S=this.W.Rw(Q,t);break a}catch(Pw){g.Zx(Pw);S=[];break a}var B=g.V2(Q);if(!B||!B.firstChild){var E=Error("Invalid caption track data");E.params=Q;throw E;}if(B.firstChild.tagName==="timedtext"){if(Number(B.firstChild.getAttribute("format"))===3){f=B;this.W||(this.W=new Fb(wi3(C),this.O$));S=this.W.Rw(f,t);break a}var r=Error("Unsupported subtitles format in web player (Format2)");r.params=Q;throw r;}if(B.firstChild.tagName===
"transcript"){var hq=Error("Unsupported subtitles format in web player (Format1)");hq.params=Q;throw hq;}var R7=Error("Invalid caption track data");R7.params=Q;throw R7;}A=x.call(l,S)}J=A}P=J}return P}catch(Pw){return this.logger.W(187101178,"Captions parsing failed: "+Pw.message+". "),this.clear(),[]}};
Hf.prototype.clear=function(){this.W&&this.W.dispose();this.W=null};
Hf.prototype.reset=function(){this.W&&this.W.reset()};
Hf.prototype.G1=function(){g.U.prototype.G1.call(this);this.clear()};var Vb={windowColor:"#080808",windowOpacity:0,textAlign:2,Nj:7,aK:50,X6:100,isDefault:!0,UQ:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.D(Ed,g.x0);g.R=Ed.prototype;g.R.G1=function(){if(this.Z||this.kf){var P=this.J.ZR();P&&!P.s$()&&P.rZ()}else xVj(this,!1);g.x0.prototype.G1.call(this)};
g.R.u0=function(){return this.O$.V("html5_honor_caption_availabilities_in_audio_track")&&this.Y!=="LIVE"&&this.Y!=="SABR_LIVE"};
g.R.yc=function(){if(this.h5)return this.Z||this.kf;var P=this.getAudioTrack();if(this.u0()){if(!P.captionTracks.length)return!1;if(!this.W)return!0}P=TOb(P,g.Po(this.O$));return P==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:P==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?Wf(this):n7y(this)||Wf(this)?!0:NQj(this)};
g.R.load=function(){g.x0.prototype.load.call(this);this.X=this.getAudioTrack();if(this.W)this.K&&(this.A5.clear(),this.Z?uDY(this,!0):this.player.getPresentingPlayerType()!==3&&this.W.Rq(this.K,"json3",this.TG),this.Z||this.kf||sd(this)||this.player.eN("captionschanged",g.Dv(this.K)));else{var P;this.Y==="OFFLINE"?P=new Gq(this.player,this.videoData,this.getAudioTrack()):this.Y==="SABR_LIVE"?P=new mVy(this.videoData.W,this.player):this.Y==="LIVE"?P=new fE(this.videoData.W,this.player):this.Y==="INNERTUBE"?
P=new g.S_(this.player,this.videoData,this.getAudioTrack()):P=new g.X0(this.player,this.videoData.t3,this.videoData.videoId,g.tcq(this.videoData),this.videoData.Cg,this.videoData.eventId);this.W=P;g.Z(this,this.W);this.W.P1(this.TG)}};
g.R.unload=function(){this.Z&&this.K?uDY(this,!1):(this.Pg&&g.t8(this.Pg),this.player.Pz("captions"),this.wM=[],this.W&&this.W.Op(),this.A5.clear(),this.Wg&&this.player.iC(this.Wg),this.t7());g.x0.prototype.unload.call(this);this.player.Gg();this.player.eN("captionschanged",{})};
g.R.create=function(){this.yc()&&this.load();var P;a:{var v,l,e;if(this.O$.V("web_player_nitrate_promo_tooltip")&&((v=this.videoData.getPlayerResponse())==null?0:(l=v.captions)==null?0:(e=l.playerCaptionsTracklistRenderer)==null?0:e.enableTouchCaptionsNitrate)){var h,z;if(v=(P=this.videoData.getPlayerResponse())==null?void 0:(h=P.captions)==null?void 0:(z=h.playerCaptionsTracklistRenderer)==null?void 0:z.captionTracks)for(P=g.N(v),h=P.next();!h.done;h=P.next())if(h=h.value,h.kind==="asr"&&h.languageCode===
"en"){P=!0;break a}}P=!1}P&&this.J.publish("showpromotooltip",this.j.element)};
g.R.E_=function(){var P=TOb(this.player.getAudioTrack(),g.Po(this.O$));var v=P==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?oU(this,this.S):P==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&Wf(this)?Od(this):n7y(this)||this.S||NQj(this)?oU(this,this.S):Wf(this)?Od(this):null;if(this.Z||this.kf){var l=g.DR(this.W.K,!0);P=[];for(var e=0;e<l.length;e++){var h=l[e],z=g.l5("TRACK");z.setAttribute("kind","subtitles");z.setAttribute("label",g.II(h));z.setAttribute("srclang",g.n_(h));z.setAttribute("id",h.toString());
this.kf||z.setAttribute("src",this.W.o2(h,"vtt"));h===v&&z.setAttribute("default","1");P.push(z)}v=this.J.ZR();v.Mu(P);P=v.YY();this.nI&&this.T1.C(P.textTracks,"change",this.gC5)}else!this.K&&v&&Tq(this,v),this.player.eN("onCaptionsTrackListChanged"),this.player.TQ("onApiChange")};
g.R.gC5=function(){for(var P=this.J.ZR().YY().textTracks,v=null,l=0;l<P.length;l++)if(P[l].mode==="showing")a:{v=g.DR(this.W.K,!0);for(var e=0;e<v.length;e++)if(v[e].toString()===P[l].id){v=v[e];break a}v=null}(this.loaded?this.K:null)!==v&&Tq(this,v,!0)};
g.R.bJW=function(){!this.K&&this.Z||this.unload()};
g.R.w2=function(P,v,l,e){if(P){var h;clQ(this,(h=this.K)!=null?h:void 0);this.W.Pc()&&(this.wM=[],this.J.Pz("captions"),yb(this.Hg),this.A5.reset());if(this.videoData.SN){var z;l=((z=l)!=null?z:0)+this.videoData.SN}P=this.A5.Rw(P,v,l,e);if(this.D3)for(v=g.N(P),l=v.next();!l.done;l=v.next())l=l.value,l.G=this.videoData.clientPlaybackNonce,l.zr=this.videoData.SN;v=!this.O$.V("html5_keep_caption_data_after_seek")&&(this.Y==="LIVE"||this.Y==="SABR_LIVE");this.player.iC(P,void 0,v);!this.S||this.kf||sd(this)||
g.pF(this.O$)||g.ZY(this.O$)||g.H$(this.O$)||this.O$.wM==="shortspage"||this.player.isInline()||(g.t8(this.Pg),P=OUd({Nj:0,aK:5,X6:5,Ta:2,textAlign:0,zJ:0,lang:"en"}),this.q5=[P],v=["Click "," for settings"],this.U$||(l=new g.wA(g.S3()),g.Z(this,l),this.U$=l.element),l=P.end-P.start,(e=g.II(this.K))&&this.q5.push(new uR(P.start,l,0,P.id,e)),this.q5.push(new uR(P.start,l,0,P.id,v[0]),new uR(P.start,l,0,P.id,this.U$,!0),new uR(P.start,l,0,P.id,v[1],!0)),this.player.iC(this.q5),g.RX(this.Pg));!this.S||
this.kf||sd(this)||(g.Po(this.O$)?rp(this,!0):MY(this,!0),this.X&&(this.X.Y=this.K),this.player.Gg());this.S=!1}};
g.R.onCueRangeEnter=function(P){this.wM.push(P);yb(this.Hg)};
g.R.onCueRangeExit=function(P){g.Tv(this.wM,P);this.W instanceof fE&&this.W.j&&this.player.j6([P]);yb(this.Hg)};
g.R.getCaptionWindowContainerId=function(){return this.j.element.id};
g.R.OXf=function(){bSy(this,this.q5);this.q5=null};
g.R.cO=function(){var P=this;if(!this.WK||!this.Z){this.Hg.stop();g.MtB(this.Ic);this.wM.sort(g.yL);var v=this.wM;if(this.Wg){var l=g.$g(v,function(z){return this.Wg.indexOf(z)===-1},this);
l.length&&(v=l)}v=g.N(v);for(l=v.next();!l.done;l=v.next())FS3(this,l.value);v=g.N(Object.entries(this.J5));var e=v.next();for(l={};!e.done;l={mK:void 0,rq:void 0},e=v.next()){var h=g.N(e.value);e=h.next().value;h=h.next().value;l.mK=e;l.rq=h;this.Ic[l.mK]?(l.rq.element.parentNode||(l.rq instanceof j7||l.rq instanceof Xb||g.cr(this.J5,function(z){return function(m,Q){Q!==z.mK&&m.K.params.Nj===z.rq.K.params.Nj&&m.K.params.aK===z.rq.K.params.aK&&m.K.params.X6===z.rq.K.params.X6&&(m.dispose(),delete P.J5[Q]);
return Q===z.mK}}(l),this),this.j.element.appendChild(l.rq.element)),l.rq.Wy(this.Ic[l.mK])):(l.rq.dispose(),delete this.J5[l.mK])}}};
g.R.GW1=function(){IHj(this,{},!0);this.player.eN("captionssettingschanged")};
g.R.nU=function(){var P=Vb.UQ;P={background:P.background,backgroundOpacity:P.backgroundOpacity,charEdgeStyle:P.charEdgeStyle,color:P.color,fontFamily:P.fontFamily,fontSizeIncrement:P.fontSizeIncrement,fontStyle:P.bold&&P.italic?3:P.bold?1:P.italic?2:0,textOpacity:P.textOpacity,windowColor:Vb.windowColor,windowOpacity:Vb.windowOpacity};var v=mTm()||{};v.background!=null&&(P.background=v.background);v.backgroundOverride!=null&&(P.backgroundOverride=v.backgroundOverride);v.backgroundOpacity!=null&&(P.backgroundOpacity=
v.backgroundOpacity);v.backgroundOpacityOverride!=null&&(P.backgroundOpacityOverride=v.backgroundOpacityOverride);v.charEdgeStyle!=null&&(P.charEdgeStyle=v.charEdgeStyle);v.charEdgeStyleOverride!=null&&(P.charEdgeStyleOverride=v.charEdgeStyleOverride);v.color!=null&&(P.color=v.color);v.colorOverride!=null&&(P.colorOverride=v.colorOverride);v.fontFamily!=null&&(P.fontFamily=v.fontFamily);v.fontFamilyOverride!=null&&(P.fontFamilyOverride=v.fontFamilyOverride);v.fontSizeIncrement!=null&&(P.fontSizeIncrement=
v.fontSizeIncrement);v.fontSizeIncrementOverride!=null&&(P.fontSizeIncrementOverride=v.fontSizeIncrementOverride);v.fontStyle!=null&&(P.fontStyle=v.fontStyle);v.fontStyleOverride!=null&&(P.fontStyleOverride=v.fontStyleOverride);v.textOpacity!=null&&(P.textOpacity=v.textOpacity);v.textOpacityOverride!=null&&(P.textOpacityOverride=v.textOpacityOverride);v.windowColor!=null&&(P.windowColor=v.windowColor);v.windowColorOverride!=null&&(P.windowColorOverride=v.windowColorOverride);v.windowOpacity!=null&&
(P.windowOpacity=v.windowOpacity);v.windowOpacityOverride!=null&&(P.windowOpacityOverride=v.windowOpacityOverride);return P};
g.R.Qe=function(P,v){var l={};Object.assign(l,mTm());Object.assign(l,P);IHj(this,l,v);this.player.eN("captionssettingschanged")};
g.R.t7=function(){!this.Z&&this.loaded&&(g.J3(this.J5,function(P,v){P.dispose();delete this.J5[v]},this),this.cO())};
g.R.hQ=function(P,v){switch(P){case "fontSize":if(isNaN(v))break;P=g.CU(v,-2,4);this.Qe({fontSizeIncrement:P});return P;case "reload":v&&!this.Z&&Tq(this,this.K,!0);break;case "stickyLoading":v!==void 0&&this.O$.j&&(g.Po(this.O$)?rp(this,!!v):MY(this,!!v));break;case "track":return Y1x(this,v);case "tracklist":return this.W?g.LC(g.DR(this.W.K,!(!v||!v.includeAsr)),function(l){return g.Dv(l)}):[];
case "translationLanguages":return this.W?this.W.Z.map(function(l){return Object.assign({},l)}):[];
case "sampleSubtitles":this.Z||v===void 0||xVj(this,!!v);break;case "sampleSubtitlesCustomized":this.Z||xVj(this,!!v,v);break;case "recommendedTranslationLanguages":return g.Og();case "defaultTranslationSourceTrackIndices":return this.W?this.W.S:[]}};
g.R.getOptions=function(){var P="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.O$.j&&P.push("stickyLoading");return P};
g.R.V8=function(){var P=this.K;if(this.J.Ap("captions")){if(this.O$.V("html5_modify_caption_vss_logging")){var v;return(P=(v=this.videoData.e0)!=null?v:null)?{cc:g.YwP(P)}:{}}if(P)return v=P.vssId,P.translationLanguage&&v&&(v="t"+v+"."+g.n_(P)),{cc:v}}return{}};
g.R.tdW=function(){this.isSubtitlesOn()?(g.Po(this.O$)?rp(this,!1):MY(this,!1),clQ(this),this.O$.V("html5_report_caption_format_change")?Tq(this,null,!0):(this.unload(),Wf(this,!0)&&Tq(this,Od(this),!1))):this.vJ()};
g.R.vJ=function(){var P=sd(this)||!this.K?oU(this,!0):this.K;this.O$.V("html5_report_caption_format_intent")&&P&&this.H9(P.vssId,"m");this.isSubtitlesOn()||Tq(this,sd(this)||!this.K?oU(this,!0):this.K,!0)};
g.R.isSubtitlesOn=function(){return!!this.loaded&&!!this.K&&!sd(this)};
g.R.hrf=function(){var P=sd(this);Wf(this,P)?Tq(this,this.getAudioTrack().W,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.u0()&&(this.S=!1,this.K=null,this.W&&(this.W.dispose(),this.W=null)),this.yc()&&(P?Tq(this,oU(this,!1),!1):this.load()))};
g.R.BX=function(P){P&&(this.QW={top:P.top,right:P.right,bottom:P.bottom,left:P.left,width:1-P.left-P.right,height:1-P.top-P.bottom},this.j.element.style.top=this.QW.top*100+"%",this.j.element.style.left=this.QW.left*100+"%",this.j.element.style.width=this.QW.width*100+"%",this.j.element.style.height=this.QW.height*100+"%",this.j.element.style.position="absolute",P=AlA(this))&&(this.j.element.style.width=P.width+"px",this.j.element.style.height=P.height+"px")};
g.R.onVideoDataChange=function(P,v){P==="newdata"&&(this.videoData=v,this.loaded&&this.unload(),this.S=!1,this.K=null,this.W&&(this.W.dispose(),this.W=null,this.player.eN("captionschanged",{})),this.yc()&&this.load())};
g.R.getAudioTrack=function(){return this.D3&&this.player.getPresentingPlayerType()===2?this.videoData.A1:this.player.getAudioTrack()};
g.R.VNg=function(){var P=this.J.ZR();P&&!P.s$()&&P.rZ();this.J.isFullscreen()?(this.Z=this.h5=!0,this.loaded&&this.E_()):(this.h5=this.O$.controlsType==="3",this.Z=$Vy(this));Tq(this,this.K)};
g.R.En=function(){var P,v,l,e=(P=this.videoData.getPlayerResponse())==null?void 0:(v=P.captions)==null?void 0:(l=v.playerCaptionsTracklistRenderer)==null?void 0:l.openTranscriptCommand;e&&this.player.C0("innertubeCommand",e)};
g.R.uh=function(P,v,l){var e=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,h="";P&&(h=P.vssId,h=h.replace(e,""));var z="";P&&P.getId()&&(z=P.getId()||"");P&&P.getXtags()&&(P=P.getXtags(),P=P.replace(e,""),z=z.concat(";"+P));this.J.uh(v?h:"",v?z:"",l)};
g.R.H9=function(P,v){P=(P||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");P.length>0&&this.J.H9(P,v)};
g.R.Ef=function(){this.W&&this.W.Ef()};
g.Wg.SJ(Ed,{cO:"smucd"});g.br("captions",Ed);})(_yt_player);
