(function(g){var window=this;'use strict';var Qpx=function(P,v){P.C0("onAutonavCoundownStarted",v)},tCd=function(P){var v,l,e;
return P==null?void 0:(v=P.playerOverlays)==null?void 0:(l=v.playerOverlayRenderer)==null?void 0:(e=l.autoplay)==null?void 0:e.playerOverlayAutoplayRenderer},Rx=function(P,v,l){g.DE(P.element,"ytp-suggestion-set",!!v.videoId);
var e=v.playlistId;l=v.MN(l?l:"mqdefault.jpg");var h=null,z=null;v instanceof g.A0&&(v.lengthText?(h=v.lengthText||null,z=v.z$||null):v.lengthSeconds&&(h=g.b4(v.lengthSeconds),z=g.b4(v.lengthSeconds,!0)));var m=!!e;e=m&&g.q3(e).type==="RD";var Q=v instanceof g.A0?v.isLivePlayback:null,t=v instanceof g.A0?v.isUpcoming:null,y=v.author,C=v.shortViewCount,f=v.publishedTimeText,k=[],w=[];y&&k.push(y);C&&(k.push(C),w.push(C));f&&w.push(f);l={title:v.title,author:y,author_and_views:k.join(" \u2022 "),aria_label:v.ariaLabel||
g.uc("Watch $TITLE",{TITLE:v.title}),duration:h,timestamp:z,url:v.Ld(),is_live:Q,is_upcoming:t,is_list:m,is_mix:e,background:l?"background-image: url("+l+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:v.fl};v instanceof g.FX&&(l.playlist_length=v.playlistLength);P.update(l)},Q6=function(P){var v=P.N(),l=v.Y;
g.O.call(this,{L:"a",D:"ytp-autonav-suggestion-card",B:{href:"{{url}}",target:l?v.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{L:"div",z1:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],B:{style:"{{background}}"},U:[{L:"div",B:{"aria-label":"{{timestamp}}"},z1:["ytp-autonav-timestamp"],Yf:"{{duration}}"},{L:"div",z1:["ytp-autonav-live-stamp"],Yf:"Live"},{L:"div",
z1:["ytp-autonav-upcoming-stamp"],Yf:"Upcoming"},{L:"div",D:"ytp-autonav-list-overlay",U:[{L:"div",D:"ytp-autonav-mix-text",Yf:"Mix"},{L:"div",D:"ytp-autonav-mix-icon"}]}]},{L:"div",z1:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Yf:"{{title}}"},{L:"div",z1:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Yf:"{{author}}"},{L:"div",z1:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Yf:"{{views_and_publish_time}}"}]});this.J=P;this.suggestion=
null;this.W=l;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},tV=function(P,v){v=v===void 0?!1:v;
g.O.call(this,{L:"div",D:"ytp-autonav-endscreen-countdown-overlay"});var l=this;this.j=v;this.cancelCommand=this.T=void 0;this.G=0;this.container=new g.O({L:"div",D:"ytp-autonav-endscreen-countdown-container"});g.Z(this,this.container);this.container.E$(this.element);v=P.N();var e=v.Y;this.J=P;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.C(P,"videodatachange",this.onVideoDataChange);this.W=new g.O({L:"div",D:"ytp-autonav-endscreen-upnext-container",B:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{L:"div",D:"ytp-autonav-endscreen-upnext-header"},{L:"div",D:"ytp-autonav-endscreen-upnext-alternative-header",Yf:"{{autoplayAlternativeHeader}}"},{L:"a",D:"ytp-autonav-endscreen-link-container",B:{href:"{{url}}",target:e?v.X:""},U:[{L:"div",D:"ytp-autonav-endscreen-upnext-thumbnail",B:{style:"{{background}}"},U:[{L:"div",B:{"aria-label":"{{timestamp}}"},z1:["ytp-autonav-timestamp"],
Yf:"{{duration}}"},{L:"div",z1:["ytp-autonav-live-stamp"],Yf:"Live"},{L:"div",z1:["ytp-autonav-upcoming-stamp"],Yf:"Upcoming"}]},{L:"div",D:"ytp-autonav-endscreen-video-info",U:[{L:"div",D:"ytp-autonav-endscreen-premium-badge"},{L:"div",D:"ytp-autonav-endscreen-upnext-title",Yf:"{{title}}"},{L:"div",D:"ytp-autonav-endscreen-upnext-author",Yf:"{{author}}"},{L:"div",D:"ytp-autonav-view-and-date",Yf:"{{views_and_publish_time}}"},{L:"div",D:"ytp-autonav-author-and-view",Yf:"{{author_and_views}}"}]}]}]});
g.Z(this,this.W);this.W.E$(this.container.element);e||this.C(this.W.cg("ytp-autonav-endscreen-link-container"),"click",this.eE);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.W.cg("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.O({L:"div",D:"ytp-autonav-overlay"});g.Z(this,this.overlay);this.overlay.E$(this.container.element);this.K=new g.O({L:"div",D:"ytp-autonav-endscreen-button-container"});g.Z(this,this.K);this.K.E$(this.container.element);
this.cancelButton=new g.O({L:"button",z1:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",v.V("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],B:{"aria-label":"Cancel autoplay"},Yf:"Cancel"});g.Z(this,this.cancelButton);this.cancelButton.E$(this.K.element);this.cancelButton.listen("click",this.Pn,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.O({L:"a",z1:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
v.V("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],B:{href:"{{url}}",role:"button","aria-label":"Play next video"},Yf:"Play Now"});g.Z(this,this.playButton);this.playButton.E$(this.K.element);this.playButton.listen("click",this.eE,this);this.J.createServerVe(this.playButton.element,this.playButton,!0);(v=this.J.getVideoData())&&ytd(this,v);this.Y=new g.mr(function(){C0Y(l)},500);
g.Z(this,this.Y);this.Rb();this.C(P,"autonavvisibility",this.Rb);this.J.V("web_autonav_color_transition")&&(this.C(P,"autonavchange",this.V5),this.C(P,"onAutonavCoundownStarted",this.Rr5))},y6=function(P){var v=P.J.Y9(!0,P.J.isFullscreen());
g.DE(P.container.element,"ytp-autonav-endscreen-small-mode",P.lA(v));g.DE(P.container.element,"ytp-autonav-endscreen-is-premium",!!P.suggestion&&!!P.suggestion.iXc);g.DE(P.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!P.J.R0());g.DE(P.J.getRootNode(),"countdown-running",P.a5());g.DE(P.container.element,"ytp-player-content",P.J.R0());g.DO(P.overlay.element,{width:v.width+"px"});if(!P.a5()){P.J.R0()?fPy(P,Math.round(g9j(P)/1E3)):fPy(P);v=!!P.suggestion&&!!P.suggestion.fl;var l=P.J.R0()||
!v;g.DE(P.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!l&&v);g.DE(P.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",l&&!v);P.K.BK(P.J.R0());g.DE(P.element,"ytp-enable-w2w-color-transitions",kQb(P))}},C0Y=function(P){var v=g9j(P),l=Math,e=l.min;
var h=P.G?Date.now()-P.G:0;l=e.call(l,h,v);fPy(P,Math.ceil((v-l)/1E3));v-l<=500&&P.a5()?P.select(!0):P.a5()&&P.Y.start()},g9j=function(P){if(P.J.isFullscreen()){var v;
P=(v=P.J.getVideoData())==null?void 0:v.j0;return P===-1||P===void 0?8E3:P}return P.J.wk()>=0?P.J.wk():g.ID(P.J.N().experiments,"autoplay_time")||1E4},ytd=function(P,v){v=v.getWatchNextResponse();
var l,e;v=(l=tCd(v))==null?void 0:(e=l.nextButton)==null?void 0:e.buttonRenderer;P.T=v==null?void 0:v.navigationEndpoint;l=v==null?void 0:v.trackingParams;P.playButton&&l&&P.J.setTrackingParams(P.playButton.element,l)},kQb=function(P){var v;
return!((v=P.J.getVideoData())==null||!v.watchToWatchTransitionRenderer)},fPy=function(P,v){v=v===void 0?-1:v;
P=P.W.cg("ytp-autonav-endscreen-upnext-header");g.z9(P);if(v>=0){v=String(v);var l="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],e="Up next in $SECONDS".indexOf(l);if(e>=0){P.appendChild(g.eu("Up next in $SECONDS".slice(0,e)));var h=g.l5("span");g.fz(h,"ytp-autonav-endscreen-upnext-header-countdown-number");g.tl(h,v);P.appendChild(h);P.appendChild(g.eu("Up next in $SECONDS".slice(e+l.length)));return}}g.tl(P,"Up next")},C4=function(P,v){g.O.call(this,{L:"div",
z1:["html5-endscreen","ytp-player-content",v||"base-endscreen"]});this.created=!1;this.player=P},f4=function(P){g.O.call(this,{L:"div",
z1:["ytp-upnext","ytp-player-content"],B:{"aria-label":"{{aria_label}}"},U:[{L:"div",D:"ytp-cued-thumbnail-overlay-image",B:{style:"{{background}}"}},{L:"span",D:"ytp-upnext-top",U:[{L:"span",D:"ytp-upnext-header",Yf:"Up Next"},{L:"span",D:"ytp-upnext-title",Yf:"{{title}}"},{L:"span",D:"ytp-upnext-author",Yf:"{{author}}"}]},{L:"a",D:"ytp-upnext-autoplay-icon",B:{role:"button",href:"{{url}}","aria-label":"Play next video"},U:[{L:"svg",B:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
U:[{L:"circle",D:"ytp-svg-autoplay-circle",B:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{L:"circle",D:"ytp-svg-autoplay-ring",B:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{L:"path",D:"ytp-svg-fill",B:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{L:"span",D:"ytp-upnext-bottom",U:[{L:"span",D:"ytp-upnext-cancel"},{L:"span",D:"ytp-upnext-paused",
Yf:"Autoplay is paused"}]}]});this.api=P;this.cancelButton=null;this.T=this.cg("ytp-svg-autoplay-ring");this.G=this.notification=this.W=this.suggestion=null;this.Y=new g.mr(this.pL,5E3,this);this.K=0;var v=this.cg("ytp-upnext-cancel");this.cancelButton=new g.O({L:"button",z1:["ytp-upnext-cancel-button","ytp-button"],B:{tabindex:"0","aria-label":"Cancel autoplay"},Yf:"Cancel"});g.Z(this,this.cancelButton);this.cancelButton.listen("click",this.rb,this);this.cancelButton.E$(v);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.Z(this,this.Y);this.api.createClientVe(this.element,this,18788);v=this.cg("ytp-upnext-autoplay-icon");this.C(v,"click",this.j1);this.api.createClientVe(v,this,115130);this.DU();this.C(P,"autonavvisibility",this.DU);this.C(P,"mdxnowautoplaying",this.PqJ);this.C(P,"mdxautoplaycanceled",this.rs$);g.DE(this.element,"ytp-upnext-mobile",this.api.N().K)},wly=function(P,v){if(v)return v;
if(P.api.isFullscreen()){var l;P=(l=P.api.getVideoData())==null?void 0:l.j0;return P===-1||P===void 0?8E3:P}return P.api.wk()>=0?P.api.wk():g.ID(P.api.N().experiments,"autoplay_time")||1E4},$Uy=function(P,v){v=wly(P,v);
var l=Math,e=l.min;var h=(0,g.Gz)()-P.K;l=e.call(l,h,v);v=v===0?1:Math.min(l/v,1);P.T.setAttribute("stroke-dashoffset",""+-211*(v+1));v>=1&&P.a5()&&P.api.getPresentingPlayerType()!==3?P.select(!0):P.a5()&&P.W.start()},g2=function(P){C4.call(this,P,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.O({L:"div",D:"ytp-suggestion-panel",U:[{L:"div",z1:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Yf:"More videos"}]});this.S=new g.O({L:"div",D:"ytp-suggestions-container"});this.videos=[];this.G=null;this.T=this.j=!1;this.K=new tV(this.player);g.Z(this,this.K);this.K.E$(this.element);P.getVideoData().vl?this.W=this.K:(this.W=new f4(P),g.i2(this.player,this.W.element,4),g.Z(this,this.W));this.overlay=new g.O({L:"div",
D:"ytp-autonav-overlay-cancelled-state"});g.Z(this,this.overlay);this.overlay.E$(this.element);this.Y=new g.Z1(this);g.Z(this,this.Y);g.Z(this,this.table);this.table.E$(this.element);this.table.show();g.Z(this,this.S);this.S.E$(this.table.element);this.hide()},kA=function(P){var v=P.R0();
v!==P.T&&(P.T=v,P.player.publish("autonavvisibility"),P.T?(P.K!==P.W&&P.K.hide(),P.table.hide()):(P.K!==P.W&&P.K.show(),P.table.show()))},w2=function(P,v){g.O.call(this,{L:"button",
z1:["ytp-watch-on-youtube-button","ytp-button"],Yf:"{{content}}"});this.J=P;this.buttonType=this.buttonType=v;this.NO();this.buttonType===2&&g.kk(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.NO);this.BK(!0)},$A=function(P,v){C4.call(this,P,"embeds-lite-endscreen");
this.J=P;this.W=v;this.J.createClientVe(this.element,this,156943);this.watchButton=new w2(P,2);g.Z(this,this.watchButton);this.watchButton.E$(this.element);this.hide()},IP3=function(P){C4.call(this,P,"subscribecard-endscreen");
this.W=new g.O({L:"div",D:"ytp-subscribe-card",U:[{L:"img",D:"ytp-author-image",B:{src:"{{profilePicture}}"}},{L:"div",D:"ytp-subscribe-card-right",U:[{L:"div",D:"ytp-author-name",Yf:"{{author}}"},{L:"div",D:"html5-subscribe-button-container"}]}]});g.Z(this,this.W);this.W.E$(this.element);var v=P.getVideoData();this.subscribeButton=new g.fh("Subscribe",null,"Unsubscribe",null,!0,!1,v.AI,v.subscribed,"trailer-endscreen",null,P,!1);g.Z(this,this.subscribeButton);this.subscribeButton.E$(this.W.cg("html5-subscribe-button-container"));
this.C(P,"videodatachange",this.b$);this.b$();this.hide()},Ix=function(P){var v=P.N(),l=g.Xs||g.xQ?{style:"will-change: opacity"}:void 0,e=v.Y,h=["ytp-videowall-still"];
v.K&&h.push("ytp-videowall-show-text");g.O.call(this,{L:"a",z1:h,B:{href:"{{url}}",target:e?v.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},U:[{L:"div",D:"ytp-videowall-still-image",B:{style:"{{background}}"}},{L:"span",D:"ytp-videowall-still-info",B:{"aria-hidden":"true"},U:[{L:"span",D:"ytp-videowall-still-info-bg",U:[{L:"span",D:"ytp-videowall-still-info-content",B:l,U:[{L:"span",D:"ytp-videowall-still-info-title",Yf:"{{title}}"},
{L:"span",D:"ytp-videowall-still-info-author",Yf:"{{author_and_views}}"},{L:"span",D:"ytp-videowall-still-info-live",Yf:"Live"},{L:"span",D:"ytp-videowall-still-info-duration",Yf:"{{duration}}"}]}]}]},{L:"span",z1:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],B:{"aria-hidden":"true"},U:[{L:"span",D:"ytp-videowall-still-listlabel-icon"},"Playlist",{L:"span",D:"ytp-videowall-still-listlabel-length",U:[" (",{L:"span",Yf:"{{playlist_length}}"},")"]}]},{L:"span",z1:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],B:{"aria-hidden":"true"},U:[{L:"span",D:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{L:"span",D:"ytp-videowall-still-listlabel-length",Yf:" (50+)"}]}]});this.suggestion=null;this.K=e;this.api=P;this.W=new g.Z1(this);g.Z(this,this.W);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.W.C(P,"videodatachange",this.onVideoDataChange);P.createServerVe(this.element,this);this.onVideoDataChange()},Da=function(P){C4.call(this,P,"videowall-endscreen");
var v=this;this.J=P;this.G=0;this.stills=[];this.Y=this.videoData=null;this.T=this.S=!1;this.X=null;this.K=new g.Z1(this);g.Z(this,this.K);this.j=new g.mr(function(){g.kk(v.element,"ytp-show-tiles")},0);
g.Z(this,this.j);var l=new g.O({L:"button",z1:["ytp-button","ytp-endscreen-previous"],B:{"aria-label":"Previous"},U:[g.cp()]});g.Z(this,l);l.E$(this.element);l.listen("click",this.qM,this);this.table=new g.wA({L:"div",D:"ytp-endscreen-content"});g.Z(this,this.table);this.table.E$(this.element);l=new g.O({L:"button",z1:["ytp-button","ytp-endscreen-next"],B:{"aria-label":"Next"},U:[g.qD()]});g.Z(this,l);l.E$(this.element);l.listen("click",this.bu,this);P.getVideoData().vl?this.W=new tV(P,!0):this.W=
new f4(P);g.Z(this,this.W);g.i2(this.player,this.W.element,4);P.createClientVe(this.element,this,158789);this.hide()},n4=function(P){return g.UR(P.player)&&P.GF()&&!P.Y},Nv=function(P){var v=P.R0();
v!==P.S&&(P.S=v,P.player.publish("autonavvisibility"))},JV=function(P){C4.call(this,P,"watch-again-on-youtube-endscreen");
this.watchButton=new w2(P,1);g.Z(this,this.watchButton);this.watchButton.E$(this.element);g.N0D(P)&&(this.W=new g.PV(P),g.Z(this,this.W),this.K=new g.O({L:"div",z1:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],B:{tabIndex:"-1"},U:[this.W]}),g.Z(this,this.K),this.W.E$(this.K.element),this.K.E$(this.element));P.createClientVe(this.element,this,156914);this.hide()},JtQ=function(P){g.x0.call(this,P);
var v=this;this.endScreen=null;this.K=this.W=this.G=this.Y=!1;this.listeners=new g.Z1(this);g.Z(this,this.listeners);var l=P.N(),e=P.getVideoData();e=e&&e.limitedPlaybackDurationInSeconds!==0;g.Iu(g.aw(l))&&e&&!g.SH(P)?(this.K=!0,this.endScreen=new $A(P,g.Dn(P))):P.isEmbedsShortsMode()?this.endScreen=new JV(P):DUj(P)?(this.Y=!0,n9b(this),this.W?this.endScreen=new g2(P):this.endScreen=new Da(P)):l.Ff?this.endScreen=new IP3(P):this.endScreen=new C4(P);g.Z(this,this.endScreen);g.i2(P,this.endScreen.element,
4);N5m(this);this.listeners.C(P,"videodatachange",this.onVideoDataChange,this);this.listeners.C(P,g.Ce("endscreen"),function(h){v.onCueRangeEnter(h)});
this.listeners.C(P,g.fe("endscreen"),function(h){v.onCueRangeExit(h)})},n9b=function(P){var v=P.player.getVideoData();
if(!v||P.W===v.iY&&P.G===v.vl)return!1;P.W=v.iY;P.G=v.vl;return!0},DUj=function(P){P=P.N();
return P.hs&&!P.Ff&&!P.disableOrganicUi},N5m=function(P){P.player.Pz("endscreen");
var v=P.player.getVideoData();v=new g.tn(Math.max((v.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var l=new g.tn(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});P.player.iC([v,l])};
g.b2.prototype.wk=g.e9(14,function(){return this.app.wk()});
g.Km.prototype.wk=g.e9(13,function(){return this.getVideoData().dF});
g.qh.prototype.Ho=g.e9(12,function(P){this.Y5().Ho(P)});
g.Yo.prototype.Ho=g.e9(11,function(P){this.W!==P&&(this.W=P,this.b$())});
g.Zz.prototype.Ho=g.e9(10,function(P){this.overflowButton&&this.overflowButton.Ho(P)});
g.qh.prototype.sX=g.e9(9,function(P){this.Y5().sX(P)});
g.SO.prototype.sX=g.e9(8,function(P){this.K!==P&&(this.K=P,this.b$())});
g.Zz.prototype.sX=g.e9(7,function(P){this.shareButton&&this.shareButton.sX(P)});
g.qh.prototype.fG=g.e9(6,function(P){this.Y5().fG(P)});
g.hY.prototype.fG=g.e9(5,function(P){this.L8!==P&&(this.L8=P,this.Dw())});
g.qh.prototype.OE=g.e9(4,function(P){this.Y5().OE(P)});
g.Zz.prototype.OE=g.e9(3,function(P){this.YX!==P&&(this.YX=P,this.lR())});g.D(Q6,g.O);Q6.prototype.select=function(){this.J.J4(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.CZ||void 0)&&this.J.logClick(this.element)};
Q6.prototype.onClick=function(P){g.Qh(P,this.J,this.W,this.suggestion.sessionData||void 0)&&this.select()};
Q6.prototype.onKeyPress=function(P){switch(P.keyCode){case 13:case 32:P.defaultPrevented||(this.select(),P.preventDefault())}};g.D(tV,g.O);g.R=tV.prototype;g.R.MF=function(P){this.suggestion!==P&&(this.suggestion=P,Rx(this.W,P),this.playButton.updateValue("url",this.suggestion.Ld()),y6(this))};
g.R.a5=function(){return this.G>0};
g.R.ZL=function(){this.a5()||(this.G=Date.now(),C0Y(this),Qpx(this.J,g9j(this)),g.DE(this.J.getRootNode(),"countdown-running",this.a5()))};
g.R.f9=function(){this.qH();C0Y(this);var P=this.W.cg("ytp-autonav-endscreen-upnext-header");P&&g.tl(P,"Up next")};
g.R.qH=function(){this.a5()&&(this.Y.stop(),this.G=0)};
g.R.select=function(P){this.J.nextVideo(!1,P===void 0?!1:P);this.qH()};
g.R.eE=function(P){g.Qh(P,this.J)&&(P.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):P.currentTarget===this.W.cg("ytp-autonav-endscreen-link-container")&&(P=this.W.cg("ytp-autonav-endscreen-link-container"),this.J.logVisibility(P,!0),this.J.logClick(P)),this.T?(this.J.C0("innertubeCommand",this.T),this.qH()):this.select())};
g.R.Pn=function(){this.J.logClick(this.cancelButton.element);g.pc(this.J,!0);this.cancelCommand&&this.J.C0("innertubeCommand",this.cancelCommand)};
g.R.onVideoDataChange=function(P,v){ytd(this,v);P=v.getWatchNextResponse();var l,e;P=(l=tCd(P))==null?void 0:(e=l.cancelButton)==null?void 0:e.buttonRenderer;this.cancelCommand=P==null?void 0:P.command};
g.R.Rr5=function(P){if(kQb(this)){var v=this.J.getVideoData().watchToWatchTransitionRenderer,l=v==null?void 0:v.fromColorPaletteDark;v=v==null?void 0:v.toColorPaletteDark;if(l&&v){var e=this.element;e.style.setProperty("--w2w-start-background-color",g.W$(l.surgeColor));e.style.setProperty("--w2w-start-primary-text-color",g.W$(l.primaryTitleColor));e.style.setProperty("--w2w-start-secondary-text-color",g.W$(l.secondaryTitleColor));e.style.setProperty("--w2w-end-background-color",g.W$(v.surgeColor));
e.style.setProperty("--w2w-end-primary-text-color",g.W$(v.primaryTitleColor));e.style.setProperty("--w2w-end-secondary-text-color",g.W$(v.secondaryTitleColor));e.style.setProperty("--w2w-animation-duration",P+"ms")}g.DE(this.element,"ytp-w2w-animate",!0)}};
g.R.V5=function(P){this.J.V("web_autonav_color_transition")&&P!==2&&g.DE(this.element,"ytp-w2w-animate",!1)};
g.R.Rb=function(){var P=this.J.R0();this.j&&this.KI!==P&&this.BK(P);y6(this);this.J.logVisibility(this.container.element,P);this.J.logVisibility(this.cancelButton.element,P);this.J.logVisibility(this.W.cg("ytp-autonav-endscreen-link-container"),P);this.J.logVisibility(this.playButton.element,P)};
g.R.lA=function(P){return P.width<400||P.height<459};g.D(C4,g.O);g.R=C4.prototype;g.R.create=function(){this.created=!0};
g.R.destroy=function(){this.created=!1};
g.R.GF=function(){return!1};
g.R.R0=function(){return!1};
g.R.Ua=function(){return!1};g.D(f4,g.O);g.R=f4.prototype;g.R.pL=function(){this.notification&&(this.Y.stop(),this.ph(this.G),this.G=null,this.notification.close(),this.notification=null)};
g.R.MF=function(P){this.suggestion=P;Rx(this,P,"hqdefault.jpg")};
g.R.DU=function(){this.BK(this.api.R0());this.api.logVisibility(this.element,this.api.R0());this.api.logVisibility(this.cg("ytp-upnext-autoplay-icon"),this.api.R0());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.R0())};
g.R.x2$=function(){window.focus();this.pL()};
g.R.ZL=function(P){var v=this;this.a5()||(g.gm("a11y-announce","Up Next "+this.suggestion.title),this.K=(0,g.Gz)(),this.W=new g.mr(function(){$Uy(v,P)},25),$Uy(this,P),Qpx(this.api,wly(this,P)));
g.$k(this.element,"ytp-upnext-autoplay-paused")};
g.R.hide=function(){g.O.prototype.hide.call(this)};
g.R.a5=function(){return!!this.W};
g.R.f9=function(){this.qH();this.K=(0,g.Gz)();$Uy(this);g.kk(this.element,"ytp-upnext-autoplay-paused")};
g.R.qH=function(){this.a5()&&(this.W.dispose(),this.W=null)};
g.R.select=function(P){P=P===void 0?!1:P;if(this.api.N().V("autonav_notifications")&&P&&window.Notification&&typeof document.hasFocus==="function"){var v=Notification.permission;v==="default"?Notification.requestPermission():v!=="granted"||document.hasFocus()||(this.pL(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.MN()}),this.G=this.C(this.notification,"click",this.x2$),this.Y.start())}this.qH();this.api.nextVideo(!1,P)};
g.R.j1=function(P){!g.Qc(this.cancelButton.element,P.target)&&g.Qh(P,this.api)&&(this.api.R0()&&this.api.logClick(this.cg("ytp-upnext-autoplay-icon")),this.select())};
g.R.rb=function(){this.api.R0()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.pc(this.api,!0)};
g.R.PqJ=function(P){this.api.getPresentingPlayerType();this.show();this.ZL(P)};
g.R.rs$=function(){this.api.getPresentingPlayerType();this.qH();this.hide()};
g.R.G1=function(){this.qH();this.pL();g.O.prototype.G1.call(this)};g.D(g2,C4);g.R=g2.prototype;g.R.create=function(){C4.prototype.create.call(this);this.Y.C(this.player,"appresize",this.dP);this.Y.C(this.player,"onVideoAreaChange",this.dP);this.Y.C(this.player,"videodatachange",this.onVideoDataChange);this.Y.C(this.player,"autonavchange",this.C4);this.Y.C(this.player,"onAutonavCancelled",this.uu);this.onVideoDataChange()};
g.R.show=function(){C4.prototype.show.call(this);(this.j||this.G&&this.G!==this.videoData.clientPlaybackNonce)&&g.pc(this.player,!1);g.UR(this.player)&&this.GF()&&!this.G?(kA(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.ZL():this.videoData.autonavState===3&&this.W.f9()):(g.pc(this.player,!0),kA(this));this.dP()};
g.R.hide=function(){C4.prototype.hide.call(this);this.W.f9();kA(this)};
g.R.dP=function(){var P=this.player.Y9(!0,this.player.isFullscreen());kA(this);y6(this.K);g.DE(this.element,"ytp-autonav-cancelled-small-mode",this.lA(P));g.DE(this.element,"ytp-autonav-cancelled-tiny-mode",this.O0(P));g.DE(this.element,"ytp-autonav-cancelled-mini-mode",P.width<=400||P.height<=360);this.overlay&&g.DO(this.overlay.element,{width:P.width+"px"});if(!this.T)for(P=0;P<this.videos.length;P++)g.DE(this.videos[P].element,"ytp-suggestion-card-with-margin",P%2===1)};
g.R.onVideoDataChange=function(){var P=this.player.getVideoData();if(this.videoData!==P&&P){this.videoData=P;if((P=this.videoData.suggestions)&&P.length||this.player.V("web_player_autonav_empty_suggestions_fix")){var v=g.er(this.videoData);v&&(this.W.MF(v),this.W!==this.K&&this.K.MF(v))}if(P&&P.length)for(v=0;v<uQd.length;++v){var l=uQd[v];if(P&&P[l]){this.videos[v]=new Q6(this.player);var e=this.videos[v];l=P[l];e.suggestion!==l&&(e.suggestion=l,Rx(e,l));g.Z(this,this.videos[v]);this.videos[v].E$(this.S.element)}}this.dP()}};
g.R.C4=function(P){P===1?(this.j=!1,this.G=this.videoData.clientPlaybackNonce,this.W.qH(),this.KI&&this.dP()):(this.j=!0,this.R0()&&(P===2?this.W.ZL():P===3&&this.W.f9()))};
g.R.uu=function(P){P?this.C4(1):(this.G=null,this.j=!1)};
g.R.GF=function(){return this.videoData.autonavState!==1};
g.R.lA=function(P){return(P.width<910||P.height<459)&&!this.O0(P)&&!(P.width<=400||P.height<=360)};
g.R.O0=function(P){return P.width<800&&!(P.width<=400||P.height<=360)};
g.R.R0=function(){return this.KI&&g.UR(this.player)&&this.GF()&&!this.G};
var uQd=[1,3,2,4];g.D(w2,g.O);g.R=w2.prototype;g.R.NO=function(){switch(this.buttonType){case 1:var P="Watch again on YouTube";var v=156915;break;case 2:P="Continue watching on YouTube";v=156942;break;default:P="Continue watching on YouTube",v=156942}this.update({content:P});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,v)};
g.R.onClick=function(P){this.J.V("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.te(this.getVideoUrl(),this.J,P);this.J.V("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.R.getVideoUrl=function(){var P=!0;switch(this.buttonType){case 1:P=!0;break;case 2:P=!1}P=this.J.getVideoUrl(P,!1,!1,!0);var v=this.J.N();if(g.LP(v)){var l={};g.LP(v)&&g.gd(this.J,"addEmbedsConversionTrackingParams",[l]);P=g.r5(P,l)}return P};
g.R.logVisibility=function(){this.J.logVisibility(this.element,this.KI&&this.Z)};
g.R.show=function(){g.O.prototype.show.call(this);this.logVisibility()};
g.R.hide=function(){g.O.prototype.hide.call(this);this.logVisibility()};
g.R.qd=function(P){g.O.prototype.qd.call(this,P);this.logVisibility()};g.D($A,C4);$A.prototype.show=function(){this.player.getPlayerState()!==3&&(C4.prototype.show.call(this),this.W.OE(!0),this.W.sX(!0),this.J.N().bC||this.W.Ho(!0),this.J.logVisibility(this.element,!0),this.watchButton.qd(!0))};
$A.prototype.hide=function(){C4.prototype.hide.call(this);this.W.OE(!1);this.W.sX(!1);this.W.Ho(!1);this.J.logVisibility(this.element,!1);this.watchButton.qd(!1)};g.D(IP3,C4);IP3.prototype.b$=function(){var P=this.player.getVideoData();this.W.update({profilePicture:P.profilePicture,author:P.author});this.subscribeButton.channelId=P.AI;var v=this.subscribeButton;P.subscribed?v.W():v.K()};g.D(Ix,g.O);Ix.prototype.select=function(){this.api.J4(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.CZ||void 0)&&this.api.logClick(this.element)};
Ix.prototype.onClick=function(P){if(g.LP(this.api.N())&&this.api.V("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var v=this.suggestion.Ld(),l={};g.Gy(this.api,l);v=g.r5(v,l);g.te(v,this.api,P)}else g.Qh(P,this.api,this.K,this.suggestion.sessionData||void 0)&&this.select()};
Ix.prototype.onKeyPress=function(P){switch(P.keyCode){case 13:case 32:P.defaultPrevented||(this.select(),P.preventDefault())}};
Ix.prototype.onVideoDataChange=function(){var P=this.api.getVideoData(),v=this.api.N();this.K=P.eg?!1:v.Y};g.D(Da,C4);g.R=Da.prototype;g.R.create=function(){C4.prototype.create.call(this);var P=this.player.getVideoData();P&&(this.videoData=P);this.g0();this.K.C(this.player,"appresize",this.g0);this.K.C(this.player,"onVideoAreaChange",this.g0);this.K.C(this.player,"videodatachange",this.onVideoDataChange);this.K.C(this.player,"autonavchange",this.zx);this.K.C(this.player,"onAutonavCancelled",this.vn);P=this.videoData.autonavState;P!==this.X&&this.zx(P);this.K.C(this.element,"transitionend",this.XzJ)};
g.R.destroy=function(){g.Bx(this.K);g.QQ(this.stills);this.stills=[];C4.prototype.destroy.call(this);g.$k(this.element,"ytp-show-tiles");this.j.stop();this.X=this.videoData.autonavState};
g.R.GF=function(){return this.videoData.autonavState!==1};
g.R.show=function(){var P=this.KI;C4.prototype.show.call(this);g.$k(this.element,"ytp-show-tiles");this.player.N().K?g.QD(this.j):this.j.start();(this.T||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.pc(this.player,!1);n4(this)?(Nv(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.ZL():this.videoData.autonavState===3&&this.W.f9()):(g.pc(this.player,!0),Nv(this));P!==this.KI&&this.player.logVisibility(this.element,!0)};
g.R.hide=function(){var P=this.KI;C4.prototype.hide.call(this);this.W.f9();Nv(this);P!==this.KI&&this.player.logVisibility(this.element,!1)};
g.R.XzJ=function(P){P.target===this.element&&this.g0()};
g.R.g0=function(){var P,v,l,e;var h=((P=this.videoData)==null?0:(v=P.suggestions)==null?0:v.length)?(l=this.videoData)==null?void 0:l.suggestions:[(e=this.videoData)==null?void 0:g.er(e)];if(h.length){g.kk(this.element,"ytp-endscreen-paginate");var z=this.J.Y9(!0,this.J.isFullscreen());if(P=g.Dn(this.J))P=P.PB()?48:32,z.width-=P*2;var m=z.width/z.height;e=96/54;v=P=2;var Q=Math.max(z.width/96,2),t=Math.max(z.height/54,2);l=h.length;var y=l*4;for(y-=4;y>0&&(P<Q||v<t);){var C=P/2,f=v/2,k=P<=Q-2&&y>=
f*4,w=v<=t-2&&y>=C*4;if((C+1)/f*e/m>m/(C/(f+1)*e)&&w)y-=C*4,v+=2;else if(k)y-=f*4,P+=2;else if(w)y-=C*4,v+=2;else break}e=!1;y>=12&&l*4-y<=6&&(v>=4||P>=4)&&(e=!0);y=P*96;Q=v*54;m=y/Q<m?z.height/Q:z.width/y;m=Math.min(m,2);y=Math.floor(Math.min(z.width,y*m));Q=Math.floor(Math.min(z.height,Q*m));z=this.table.element;z.ariaLive="polite";g.Ln(z,y,Q);g.DO(z,{marginLeft:y/-2+"px",marginTop:Q/-2+"px"});this.W.MF(g.er(this.videoData));this.W instanceof tV&&y6(this.W);g.DE(this.element,"ytp-endscreen-takeover",
n4(this));Nv(this);y+=4;Q+=4;m=0;z.ariaBusy="true";for(t=0;t<P;t++)for(C=0;C<v;C++)if(f=m,w=0,e&&t>=P-2&&C>=v-2?w=1:C%2===0&&t%2===0&&(C<2&&t<2?C===0&&t===0&&(w=2):w=2),f=g.kr(f+this.G,l),w!==0){k=this.stills[m];k||(k=new Ix(this.player),this.stills[m]=k,z.appendChild(k.element));var I=Math.floor(Q*C/v),J=Math.floor(y*t/P),K=Math.floor(Q*(C+w)/v)-I-4,q=Math.floor(y*(t+w)/P)-J-4;g.ck(k.element,J,I);g.Ln(k.element,q,K);g.DO(k.element,"transitionDelay",(C+t)/20+"s");g.DE(k.element,"ytp-videowall-still-mini",
w===1);g.DE(k.element,"ytp-videowall-still-large",w>2);w=Math.max(q,K);g.DE(k.element,"ytp-videowall-still-round-large",w>=256);g.DE(k.element,"ytp-videowall-still-round-medium",w>96&&w<256);g.DE(k.element,"ytp-videowall-still-round-small",w<=96);f=h[f];k.suggestion!==f&&(k.suggestion=f,w=k.api.N(),I=g.gt(k.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",Rx(k,f,I),g.LP(w)&&!k.api.V("web_player_log_click_before_generating_ve_conversion_params")&&(w=f.Ld(),I={},g.gd(k.api,"addEmbedsConversionTrackingParams",
[I]),w=g.r5(w,I),k.updateValue("url",w)),(f=(f=f.sessionData)&&f.itct)&&k.api.setTrackingParams(k.element,f));m++}z.ariaBusy="false";g.DE(this.element,"ytp-endscreen-paginate",m<l);for(h=this.stills.length-1;h>=m;h--)P=this.stills[h],g.Re(P.element),g.Rm(P);this.stills.length=m}};
g.R.onVideoDataChange=function(){var P=this.player.getVideoData(1);this.videoData!==P&&(P!=null&&g.er(P)?(this.G=0,this.videoData=P,this.g0()):this.player.f0("missg",{vid:(P==null?void 0:P.videoId)||"",cpn:(P==null?void 0:P.clientPlaybackNonce)||""}))};
g.R.bu=function(){this.G+=this.stills.length;this.g0()};
g.R.qM=function(){this.G-=this.stills.length;this.g0()};
g.R.Ua=function(){return this.W.a5()};
g.R.zx=function(P){P===1?(this.T=!1,this.Y=this.videoData.clientPlaybackNonce,this.W.qH(),this.KI&&this.g0()):(this.T=!0,this.KI&&n4(this)&&(P===2?this.W.ZL():P===3&&this.W.f9()))};
g.R.vn=function(P){if(P){for(P=0;P<this.stills.length;P++)this.J.logVisibility(this.stills[P].element,!0);this.zx(1)}else this.Y=null,this.T=!1;this.g0()};
g.R.R0=function(){return this.KI&&n4(this)};g.D(JV,C4);JV.prototype.hasSuggestions=function(){var P;return(P=this.W)==null?void 0:P.hasSuggestions()};
JV.prototype.show=function(){if(this.player.getPlayerState()!==3){C4.prototype.show.call(this);var P=this.K;if(P){var v=this.W.hasSuggestions();g.DE(this.element,"ytp-shorts-branded-ui",v);v?P.show():P.hide()}var l;(l=g.Dn(this.player))==null||l.fG(!0);this.player.logVisibility(this.element,!0);this.watchButton.qd(!0)}};
JV.prototype.hide=function(){C4.prototype.hide.call(this);var P;(P=g.Dn(this.player))==null||P.fG(!1);this.player.logVisibility(this.element,!1);this.watchButton.qd(!1)};g.D(JtQ,g.x0);g.R=JtQ.prototype;g.R.yc=function(){var P=this.player.getVideoData(),v=P.V("embeds_enable_full_length_inline_muted_autoplay")?P.mutedAutoplay&&(P.limitedPlaybackDurationInSeconds>0||P.endSeconds>0):P.mutedAutoplay;if((this.player.isEmbedsShortsMode()||this.K)&&!v)return!0;var l;var e=!!((P==null?0:g.er(P))||(P==null?0:(l=P.suggestions)==null?0:l.length));e=!DUj(this.player)||e;P=P.jb;l=this.player.Qn();return e&&!P&&!l&&!v};
g.R.R0=function(){return this.endScreen.R0()};
g.R.jc5=function(){return this.R0()?this.endScreen.Ua():!1};
g.R.G1=function(){this.player.Pz("endscreen");g.x0.prototype.G1.call(this)};
g.R.load=function(){var P=this.player.getVideoData();var v=P.transitionEndpointAtEndOfStream;if(v&&v.videoId){var l=this.player.Oi().NV.get("heartbeat"),e=g.er(P);!e||v.videoId!==e.videoId||P.mE?(this.player.J4(v.videoId,void 0,void 0,!0,!0,v),l&&l.p5("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),P=!0):P=!1}else P=!1;P||(g.x0.prototype.load.call(this),this.endScreen.show())};
g.R.unload=function(){g.x0.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.R.onCueRangeEnter=function(P){this.yc()&&(this.endScreen.created||this.endScreen.create(),P.getId()==="load"&&this.load())};
g.R.onCueRangeExit=function(P){P.getId()==="load"&&this.loaded&&this.unload()};
g.R.onVideoDataChange=function(){N5m(this);this.Y&&n9b(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.W?this.endScreen=new g2(this.player):this.endScreen=new Da(this.player),g.Z(this,this.endScreen),g.i2(this.player,this.endScreen.element,4))};g.br("endscreen",JtQ);})(_yt_player);
