(function(g){var window=this;'use strict';var XM=function(P,v){g.O.call(this,{L:"button",z1:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],B:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},U:[{L:"svg",B:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},U:[{L:"g",B:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},U:[{L:"g",B:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
U:[{L:"path",B:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=P;this.listen("click",this.onClick,this);this.updateValue("title",g.Yi(P,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.Fo(v.FE(),this.element))},NFx=function(P){g.O.call(this,
{L:"div",
D:"ytp-miniplayer-ui"});this.S=this.T=!1;this.player=P;this.C(P,"minimized",this.JQ);this.C(P,"onStateChange",this.gF3);this.C(P,"documentpictureinpicturechange",this.QVJ)},J4o=function(P,v){g.DE(P.player.getRootNode(),"ytp-player-minimized",v);
P.player.V("web_cairo_modern_miniplayer")&&g.DE(P.player.getRootNode(),"ytp-modern-miniplayer",v);P.player.V("web_cairo_modern_miniplayer_inset_progress_bar")&&g.DE(P.player.getRootNode(),"ytp-miniplayer-alternate-ui",v)},uF3=function(P){var v=P.player.S2().getPlayerSize().width,l=0,e=v;
if(P.player.V("web_cairo_modern_miniplayer")&&!P.S&&!P.player.V("web_cairo_modern_miniplayer_infobar")||P.player.V("web_cairo_modern_miniplayer_inset_progress_bar"))l=12,e=v-24;g.Zux(P.progressBar,l,e,!1);g.Pg(P.progressBar)},K3x=function(P){g.x0.call(this,P);
this.K=new g.Z1(this);this.W=new NFx(this.player);this.W.hide();g.i2(this.player,this.W.element,4);P.isMinimized()&&(this.load(),g.DE(P.getRootNode(),"ytp-player-minimized",!0))};
g.D(XM,g.O);XM.prototype.onClick=function(){this.J.C0("onExpandMiniplayer")};g.D(NFx,g.O);g.R=NFx.prototype;
g.R.show=function(){this.W=new g.zl(this.hG,null,this);this.W.start();if(!this.T){this.tooltip=new g.U4(this.player,this);g.Z(this,this.tooltip);g.i2(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.zP=new g.QE(this.player);g.Z(this,this.zP);this.progressBar=new g.d8(this.player,this);g.Z(this,this.progressBar);g.i2(this.player,this.progressBar.element,4);this.player.V("web_cairo_modern_miniplayer_infobar")&&g.kk(this.player.getRootNode(),"ytp-always-showing-infobar");this.K=new g.O({L:"div",
D:"ytp-miniplayer-scrim"});g.Z(this,this.K);this.K.E$(this.element);this.C(this.K.element,"click",this.VB);var P=new g.O({L:"button",z1:["ytp-miniplayer-close-button","ytp-button"],B:{"aria-label":"Close"},U:[g.Fq()]});g.Z(this,P);P.E$(this.K.element);this.C(P.element,"click",this.d_);P=new XM(this.player,this);g.Z(this,P);P.E$(this.K.element);this.G=new g.O({L:"div",D:"ytp-miniplayer-controls"});g.Z(this,this.G);this.G.E$(this.K.element);this.player.V("web_cairo_modern_miniplayer")||this.C(this.G.element,
"click",this.VB);var v=new g.O({L:"div",D:"ytp-miniplayer-button-container"});g.Z(this,v);v.E$(this.G.element);P=new g.O({L:"div",D:"ytp-miniplayer-play-button-container"});g.Z(this,P);P.E$(this.G.element);var l=new g.O({L:"div",D:"ytp-miniplayer-button-container"});g.Z(this,l);l.E$(this.G.element);this.X=new g.sT(this.player,this,!1);g.Z(this,this.X);this.X.E$(v.element);v=new g.o$(this.player,this);g.Z(this,v);v.E$(P.element);this.nextButton=new g.sT(this.player,this,!0);g.Z(this,this.nextButton);
this.nextButton.E$(l.element);this.j=this.player.V("web_cairo_modern_miniplayer")?new g.be(this.player,this,0):new g.be(this.player,this);g.Z(this,this.j);this.j.E$(this.K.element);this.Y=new g.O({L:"div",D:"ytp-miniplayer-buttons"});g.Z(this,this.Y);g.i2(this.player,this.Y.element,4);P=new g.O({L:"button",z1:["ytp-miniplayer-close-button","ytp-button"],B:{"aria-label":"Close"},U:[g.Fq()]});g.Z(this,P);P.E$(this.Y.element);this.C(P.element,"click",this.d_);P=new g.O({L:"button",z1:["ytp-miniplayer-replay-button",
"ytp-button"],B:{"aria-label":"Close"},U:[g.Lv()]});g.Z(this,P);P.E$(this.Y.element);this.C(P.element,"click",this.Z6W);this.player.V("web_cairo_modern_miniplayer")&&(P=new XM(this.player,this),g.Z(this,P),P.E$(this.Y.element));this.C(this.player,"presentingplayerstatechange",this.Rp);this.C(this.player,"appresize",this.lQ);this.C(this.player,"fullscreentoggled",this.lQ);this.player.V("web_cairo_modern_miniplayer")&&this.C(this.player,"onPlaylistUpdate",this.eX);this.lQ();this.T=!0}this.player.getPlayerState()!==
0&&g.O.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.R.hide=function(){this.W&&(this.W.dispose(),this.W=void 0);g.O.prototype.hide.call(this);this.player.isMinimized()||(this.T&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.R.G1=function(){this.W&&(this.W.dispose(),this.W=void 0);g.O.prototype.G1.call(this)};
g.R.d_=function(){this.player.V("kevlar_watch_while_v2")||this.player.stopVideo();this.player.C0("onCloseMiniplayer")};
g.R.Z6W=function(){this.player.playVideo()};
g.R.VB=function(P){if(P.target===this.K.element||P.target===this.G.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.R.JQ=function(){J4o(this,this.player.isMinimized());this.player.V("web_cairo_modern_miniplayer")&&this.eX()};
g.R.QVJ=function(){J4o(this,this.player.Kq());this.player.V("web_cairo_modern_miniplayer")&&this.eX();g.DE(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.Kq())};
g.R.mf=function(){this.progressBar.sb();this.j.sb()};
g.R.hG=function(){this.mf();this.W&&this.W.start()};
g.R.Rp=function(P){g.M(P.state,32)&&this.tooltip.hide()};
g.R.eX=function(){this.S=(this.player.isMinimized()||this.player.Kq())&&!!this.player.getPlaylist();g.DE(this.player.getRootNode(),"ytp-has-playlist-data",this.S);uF3(this)};
g.R.lQ=function(){uF3(this)};
g.R.gF3=function(P){this.player.isMinimized()&&(P===0?this.hide():this.show())};
g.R.FE=function(){return this.tooltip};
g.R.Wv=function(P,v,l,e,h){var z=0,m=0,Q=0,t=g.S8(P);e=v&&(g.gt(v,"ytp-prev-button")||g.gt(v,"ytp-next-button"));if(v){l=g.gt(v,"ytp-play-button");var y=g.gt(v,"ytp-miniplayer-expand-watch-page-button");e?z=Q=12:l?(v=g.pn(v,this.element),Q=v.x,z=v.y-12):y&&(Q=g.gt(v,"ytp-miniplayer-button-top-left"),z=g.pn(v,this.element),v=g.S8(v),Q?(Q=8,z=z.y+40):(Q=z.x-t.width+v.width,z=z.y-20))}else Q=l-t.width/2,m=25+(h||0);v=this.player.S2().getPlayerSize();h=z+(h||0);t=g.CU(Q,0,v.width-t.width-12);h?(P.style.top=
h+"px",P.style.bottom=""):(P.style.top="",P.style.bottom=m+"px");P.style.left=t+"px";this.player.V("web_cairo_modern_miniplayer")&&(m=g.gt(P,"ytp-preview"),P.style.visibility=e&&m&&v.height<225?"hidden":"")};g.D(K3x,g.x0);g.R=K3x.prototype;g.R.onVideoDataChange=function(){if(this.player.getVideoData()){var P=this.player.getVideoAspectRatio(),v=16/9;P=P>v+.1||P<v-.1;g.DE(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",P)}};
g.R.create=function(){g.x0.prototype.create.call(this);this.K.C(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.R.x9=function(){return!1};
g.R.load=function(){this.player.hideControls();this.W.show()};
g.R.unload=function(){this.player.showControls();this.W.hide()};g.br("miniplayer",K3x);})(_yt_player);
